server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name readers.lubimovka.art;
    include /config/nginx/ssl.conf;

    client_max_body_size 20M;

    location /static/ {
        alias /lubimovka-readers/static_content/;
        expires 30d;
        access_log off;
    }

    location / {
        include /config/nginx/proxy.conf;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        set $upstream_app lubimovka_readers;
        set $upstream_port 8000;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
