# Generated by Django 3.2.7 on 2021-10-02 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Базовое событие',
                'verbose_name_plural': 'Базовые события',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('performance', 'Спектакль'), ('masterclass', 'Мастер-класс'), ('reading', 'Читка')], default='performance', max_length=50, verbose_name='Тип события')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('paid', models.BooleanField(verbose_name='Платное')),
                ('url', models.URLField(blank=True, unique=True, verbose_name='Ссылка')),
                ('place', models.CharField(max_length=200, verbose_name='Место')),
                ('base_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body', to='afisha.baseevent', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ('-created',),
            },
        ),
    ]
