# Generated by Django 3.2.7 on 2021-10-07 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_auto_20211002_2212'),
        ('afisha', '0003_baseevent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaseEvent',
            new_name='CommonEvent',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created',), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='common_event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='body', to='afisha.commonevent', verbose_name='Событие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Платное'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='Место', max_length=200, verbose_name='Место'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Спектакль', 'Спектакль'), ('Мастер-класс', 'Мастер-класс'), ('Читка', 'Читка')], default='Спектакль', max_length=50, verbose_name='Тип события'),
        ),
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, unique=True, verbose_name='Ссылка'),
        ),
    ]
