# Generated by Django 3.2.12 on 2022-03-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afisha", "0003_remove_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="type",
            field=models.CharField(
                choices=[("PERFORMANCE", "Спектакль"), ("MASTERCLASS", "Мастер-класс"), ("READING", "Читка")],
                max_length=50,
                verbose_name="Тип события",
            ),
        ),
    ]
