# Generated by Django 3.2.9 on 2021-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0005_alter_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pinned_on_main',
            field=models.BooleanField(default=False, verbose_name='Закрепить на главной'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'Спектакль'), ('MASTERCLASS', 'Мастер-класс'), ('READING', 'Читка')], max_length=50, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(verbose_name='Ссылка'),
        ),
    ]
