# Generated by Django 3.2.13 on 2022-05-18 11:48

import apps.content_pages.utilities
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20220427_1531'),
        ('core', '0017_data_additional_and_updated_email_settings'),
        ('library', '0026_auto_20220509_1311'),
        ('afisha', '0005_alter_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('events', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reading', to='afisha.commonevent', verbose_name='События')),
                ('persons', models.ManyToManyField(related_name='readings', through='library.TeamMember', to='core.Person', verbose_name='Члены команды')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='library.play', verbose_name='Пьеса')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='articles.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Читка',
                'verbose_name_plural': 'Читки',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROCESS', 'В работе'), ('REVIEW', 'На проверке'), ('READY_FOR_PUBLICATION', 'Готово к публикации'), ('PUBLISHED', 'Опубликовано'), ('REMOVED_FROM_PUBLICATION', 'Снято с публикации')], default='IN_PROCESS', max_length=35, verbose_name='Статус')),
                ('name', models.CharField(max_length=200, verbose_name='Название спектакля')),
                ('main_image', models.ImageField(upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Главное изображение')),
                ('bottom_image', models.ImageField(upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Изображение внизу страницы')),
                ('video', models.URLField(blank=True, null=True, unique=True, verbose_name='Видео')),
                ('description', models.TextField(max_length=500, verbose_name='Краткое описание')),
                ('text', models.TextField(max_length=2000, verbose_name='Полное описание')),
                ('age_limit', models.IntegerField(choices=[(0, '0+'), (6, '6+'), (12, '12+'), (13, '13+'), (16, '16+'), (17, '17+'), (18, '18+')], default=0, verbose_name='Возрастное ограничение')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=5100), verbose_name='Продолжительность')),
                ('events', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='performance', to='afisha.commonevent', verbose_name='События')),
                ('persons', models.ManyToManyField(related_name='performances', through='library.TeamMember', to='core.Person', verbose_name='Члены команды')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performances', to='library.play', verbose_name='Пьеса')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='articles.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
                'ordering': ('-created',),
                'permissions': (('access_level_1', 'Права журналиста'), ('access_level_2', 'Права редактора'), ('access_level_3', 'Права главреда')),
            },
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('events', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='masterclass', to='afisha.commonevent', verbose_name='События')),
                ('persons', models.ManyToManyField(related_name='masterclasses', through='library.TeamMember', to='core.Person', verbose_name='Члены команды')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterclasses', to='articles.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Мастер-класс',
                'verbose_name_plural': 'Мастер-классы',
                'ordering': ('-created',),
            },
        ),
    ]
