# Generated by Django 3.2.13 on 2022-05-27 07:08

import apps.content_pages.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_data_additional_and_updated_email_settings'),
        ('afisha', '0006_masterclass_performance_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('reviewer_name', models.CharField(max_length=100, verbose_name='Имя зрителя')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст отзыва')),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на отзыв')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='afisha.performance', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Отзыв зрителя на спектакль',
                'verbose_name_plural': 'Отзывы зрителей на спектакль',
                'db_table': 'performance_review',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PerformanceMediaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('media_name', models.CharField(max_length=100, verbose_name='Название медиа ресурса')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст отзыва')),
                ('image', models.ImageField(upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Изображение')),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='Ссылка на отзыв')),
                ('pub_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_reviews', to='afisha.performance', verbose_name='Спектакль')),
            ],
            options={
                'verbose_name': 'Медиа отзыв на спектакль',
                'verbose_name_plural': 'Медиа отзывы на спектакль',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PerformanceImage',
            fields=[
                ('image_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.image')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_in_block', to='afisha.performance', verbose_name='Изображения спектакля')),
            ],
            options={
                'db_table': 'performance_image',
            },
            bases=('core.image',),
        ),
    ]
