# Generated by Django 3.2.9 on 2021-11-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0006_auto_20211127_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date_time',), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
    ]
