# Generated by Django 3.2.13 on 2022-05-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0006_masterclass_performance_reading'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='masterclass',
            table='masterclass',
        ),
        migrations.AlterModelTable(
            name='performance',
            table='performance',
        ),
        migrations.AlterModelTable(
            name='reading',
            table='reading',
        ),
    ]
