# Generated by Django 3.2.13 on 2022-06-08 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afisha', '0008_load_creatorsss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='Создатель'),
        ),
    ]
