# Generated by Django 3.2.13 on 2022-07-10 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0011_again_overwrite_creators_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5100), help_text='Введите продолжительность в формате ЧЧ:ММ:СС', verbose_name='Продолжительность'),
        ),
    ]
