# Generated by Django 3.2.13 on 2022-07-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0012_auto_20220708_0358'),
        ('afisha', '0013_delete_permission_preamble_title_text_qoute'),
    ]

    operations = [
    ]
