# Generated by Django 3.2.13 on 2022-07-12 16:12
from django.db import migrations


def delete_permission(apps, schema_editor):
    """Remove not supported content from projects."""
    PermissionType = apps.get_model("auth", "Permission")

    PermissionType.objects.filter(content_type__model="preamble").delete()
    PermissionType.objects.filter(content_type__model="quote").delete()
    PermissionType.objects.filter(content_type__model="text").delete()
    PermissionType.objects.filter(content_type__model="title").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0013_auto_20220708_0358'),
    ]

    operations = [
        migrations.RunPython(
            delete_permission,
        ),
    ]
