# Generated by Django 3.2.13 on 2022-07-14 15:58

from django.db import migrations, models

from apps.core import utils


def set_slug(apps, schema_editor):
    Performance = apps.get_model("afisha", "Performance")
    qs = Performance.objects.all()
    for performance in qs:
        name_with_underscore = performance.name.replace(" ", "_")
        performance.slug = utils.slugify(name_with_underscore)
        performance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0014_merge_20220713_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='slug',
            field=models.SlugField(max_length=200, blank=True, error_messages={'unique': 'Такой транслит уже используется, введите иной'}, help_text='Формируется автоматически, может быть изменен вручную', verbose_name='Транслит названия для формирования адресной строки'),
        ),
        migrations.RunPython(
            set_slug,
        ),
        migrations.AlterField(
            model_name='performance',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'Такой транслит уже используется, введите иной'}, help_text='Формируется автоматически, может быть изменен вручную', max_length=200, unique=True, verbose_name='Транслит названия для формирования адресной строки'),
        ),
    ]
