# Generated by Django 3.2.13 on 2022-07-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0015_auto_20220714_2336'),
        ('afisha', '0015_remove_event_place'),
    ]

    operations = [
    ]
