# Generated by Django 3.2.13 on 2022-07-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0015_auto_20220715_1417'),
        ('afisha', '0016_merge_0015_auto_20220714_2336_0015_remove_event_place'),
    ]

    operations = [
    ]
