# Generated by Django 3.2.13 on 2022-07-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0017_remove_event_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ('name',), 'permissions': (('access_level_1', 'Права журналиста'), ('access_level_2', 'Права редактора'), ('access_level_3', 'Права главреда')), 'verbose_name': 'Спектакль', 'verbose_name_plural': 'Спектакли'},
        ),
    ]
