# Generated by Django 3.2.13 on 2022-07-15 11:17

import apps.content_pages.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0017_alter_performance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='reading',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='supplemental_text',
            field=models.TextField(blank=True, help_text='Описание, расположенное под изображением', max_length=500, verbose_name='Дополнительное описание'),
        ),
        migrations.AddField(
            model_name='reading',
            name='supplemental_text',
            field=models.TextField(blank=True, help_text='Описание, расположенное под изображением', max_length=500, verbose_name='Дополнительное описание'),
        ),
    ]
