# Generated by Django 3.2.14 on 2022-08-04 08:36

import apps.content_pages.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0018_auto_20220715_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemediareview',
            name='image',
            field=models.ImageField(upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Логотип медиа ресурса'),
        ),
    ]
