# Generated by Django 3.2.13 on 2022-07-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0017_alter_performance_options'),
        ('afisha', '0018_auto_20220724_1951'),
    ]

    operations = [
    ]
