# Generated by Django 3.2.13 on 2022-08-05 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0019_alter_performancemediareview_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masterclass',
            old_name='supplemental_text',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='performance',
            old_name='supplemental_text',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='reading',
            old_name='supplemental_text',
            new_name='intro',
        ),
    ]
