# Generated by Django 3.2.14 on 2022-09-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0020_auto_20220806_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='button',
            field=models.CharField(choices=[('REGISTRATION', 'Регистрация'), ('TICKETS', 'Билеты'), ('STREAM', 'Трансляция')], default='REGISTRATION', help_text='Выберите описание действия кнопки, соответсвующее ссылке', max_length=50, verbose_name='Тип кнопки'),
        ),
    ]
