# Generated by Django 3.2.13 on 2022-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0021_event_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='pinned_on_main',
        ),
        migrations.AddField(
            model_name='event',
            name='hidden_on_main',
            field=models.BooleanField(default=True, verbose_name='Скрыть на главной'),
        ),
    ]
