# Generated by Django 3.2.14 on 2022-10-10 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0022_auto_20220921_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='action',
            new_name='action_text',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='url',
            new_name='action_url',
        ),
    ]
