# Generated by Django 3.2.16 on 2023-01-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0023_auto_20221010_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='opening_interval',
            field=models.PositiveSmallIntegerField(blank=True, default=720, help_text='Введите за сколько минут до начала открывается регистрация', null=True, verbose_name='Интервал открытия регистрации'),
        ),
    ]
