# Generated by Django 3.2.16 on 2023-02-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0023_auto_20221010_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
