# Generated by Django 3.2.16 on 2023-02-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0024_alter_event_action_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='action_text',
            field=models.CharField(blank=True, choices=[('REGISTRATION', 'Регистрация'), ('TICKETS', 'Билеты'), ('STREAM', 'Трансляция')], help_text='Выберите название действия, соответсвующее содержанию ссылки', max_length=50, verbose_name='Название действия'),
        ),
    ]
