# Generated by Django 3.2.18 on 2023-05-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0025_alter_event_action_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='project',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='project',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='project',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Место'),
        ),
    ]
