# Generated by Django 3.2.18 on 2023-05-30 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0040_auto_20230530_0257'),
        ('afisha', '0026_auto_20230512_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='persons',
        ),
        migrations.AlterField(
            model_name='event',
            name='common_event',
            field=models.ForeignKey(help_text='Создайте спектакль или читку чтобы получить возможность создать соответствующее событие', on_delete=django.db.models.deletion.CASCADE, related_name='body', to='afisha.commonevent', verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'Спектакль'), ('READING', 'Читка')], help_text='Выберите тип события', max_length=50, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='play',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='library.play', verbose_name='Пьеса'),
        ),
    ]
