# Generated by Django 3.2.18 on 2023-05-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0028_auto_20230530_0311'),
        ('library', '0041_add_removed_constraint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterClass',
        ),
    ]
