FROM python:3.9
WORKDIR /code
COPY .  .
COPY requirements/ requirements/
RUN python -m pip install --upgrade pip
RUN pip install -r requirements/prod.txt
CMD gunicorn config.wsgi:application -c /code/gunicorn.conf.py
