version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres_develop
    restart: always
    volumes:
      - postgres_data_develop:/var/lib/postgresql/data
    env_file:
      - .env-dev
    networks:
      - develop_db_network
  backend:
    image: "${IMAGE_BACK}:${IMAGE_BACK_TAG}"
    container_name: backend_develop
    restart: always
    volumes:
      - static_value_develop:/code/staticfiles/
      - media_value_develop:/code/media/
    depends_on:
      - postgres
    env_file:
      - .env-dev
    networks:
      - develop_db_network
      - develop_swag_network
  migrations:
    image: "${IMAGE_BACK}:${IMAGE_BACK_TAG}"
    container_name: migrations_develop
    volumes:
      - static_value_develop:/code/staticfiles/
      - media_value_develop:/code/media/
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput"
    depends_on:
      - backend
    env_file:
      - .env-dev
    networks:
      - develop_db_network
  swag:
    image: hcr.io/linuxserver/swag:1.22.0
    container_name: swag_develop
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Moscow
      - VALIDATION=http
#      - SUBDOMAINS=${DEV_SUBDOMAIN},${TEST_SUBDOMAIN}
      - SUBDOMAINS=${DEV_SUBDOMAIN}
      - ONLY_SUBDOMAINS=true
      - CERTPROVIDER=zerossl
    env_file:
      - .env-dev
    networks:
      - develop_swag_network
    volumes:
      - ./swag/swag_nginx_develop.conf:/config/nginx/site-confs/default
      - static_value_develop:/config/develop/static/
      - media_value_develop:/config/develop/media/
      - static_value_test:/config/test/static/
      - media_value_test:/config/test/media/
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

networks:
  develop_db_network:
    name: develop_db_network
  develop_swag_network:
    name: develop_swag_network
    external: true

volumes:
  postgres_data_develop:
    name: postgres_data_develop
  static_value_develop:
    name: static_value_develop
  media_value_develop:
    name: media_value_develop
  static_value_test:
    name: static_value_test
  media_value_test:
    name: media_value_test
