version: '3.8'

services:
  swag:
    image: ghcr.io/linuxserver/swag:1.22.0
    container_name: swag_develop
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Moscow
      - VALIDATION=http
#      - SUBDOMAINS=${DEV_SUBDOMAIN},${TEST_SUBDOMAIN}
      - SUBDOMAINS=${DEV_SUBDOMAIN}
      - ONLY_SUBDOMAINS=true
      - CERTPROVIDER=zerossl
    env_file:
      - .env-dev
    networks:
      - develop_swag_network
    volumes:
      - ./swag/swag_nginx_develop.conf:/config/nginx/site-confs/default
      - static_value_develop:/config/develop/static/
      - media_value_develop:/config/develop/media/
      - static_value_test:/config/test/static/
      - media_value_test:/config/test/media/
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  frontend_develop:
    image: "${IMAGE_FRONT}:${IMAGE_FRONT_TAG}"
    container_name: frontend_develop
    environment:
      BASE_URL: ${FRONT_BASE_URL}
      API_BASE_URL: ${DEVELOP_API_BASE_URL}
    networks:
      - develop_swag_network
    ports:
      - "3005:3000"
    restart: always
    depends_on:
      - swag
  frontend_test:
    image: "${IMAGE_FRONT}:${IMAGE_FRONT_TAG}"
    container_name: frontend_test
    environment:
      BASE_URL: ${FRONT_BASE_URL}
      API_BASE_URL: ${TEST_API_BASE_URL}
    networks:
      - develop_swag_network
    ports:
      - "3004:3000"
    restart: always
    depends_on:
      - swag

networks:
  develop_swag_network:
    name: develop_swag_network

volumes:
  static_value_test:
    name: static_value_test
  media_value_test:
    name: media_value_test
  static_value_develop:
    name: static_value_develop
  media_value_develop:
    name: media_value_develop
