version: '3.8'

services:
  frontend_develop:
    image: "${IMAGE_FRONT}:${IMAGE_FRONT_TAG}"
    container_name: frontend_develop
    environment:
      BASE_URL: ${FRONT_BASE_URL}
      API_BASE_URL: ${DEVELOP_API_BASE_URL}
    networks:
      - develop_swag_network
    ports:
      - "3005:3000"
    restart: always
  frontend_test:
    image: "${IMAGE_FRONT}:${IMAGE_FRONT_TAG}"
    container_name: frontend_test
    environment:
      BASE_URL: ${FRONT_BASE_URL}
      API_BASE_URL: ${TEST_API_BASE_URL}
    networks:
      - develop_swag_network
    ports:
      - "3004:3000"
    restart: always

networks:
  develop_swag_network:
    name: develop_swag_network
    external: true
  develop_db_network:
    name: develop_db_network
    external: true
