services:
  postfix:
    build:
      context: .
      args:
        - POSTFIX_HOSTNAME=$POSTFIX_HOSTNAME
        - DEBIAN_MAILNAME=$POSTFIX_MAIL_DOMAIN
    env_file:
      - ../.env-test
    container_name: postfix
    ports:
      - 25:25
    volumes:
      - ./mail:/var/spool/mail
      - config:/etc/postfix
    networks:
      - test_db_network
    logging:
      driver: journald
    restart: unless-stopped
volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: ./config
      o: bind
networks:
  test_db_network:
    name: test_db_network
    external: true
