services:
  postfix:
    build:
      context: .
      args:
        - POSTFIX_HOSTNAME=$POSTFIX_HOSTNAME
        - DEBIAN_MAILNAME=$POSTFIX_MAIL_DOMAIN
    env_file:
      - ../.env-prod
    container_name: postfix
    ports:
      - 25:25
    volumes:
      - ./mail:/var/spool/mail
      - ./config:/etc/postfix
    networks:
      - prod_db_network
    logging:
      driver: journald
    restart: unless-stopped
networks:
  prod_db_network:
    name: prod_db_network
    external: true
