version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres_prod
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env-prod
    networks:
      - prod_db_network
  backend:
    image: "${IMAGE_BACK}:${IMAGE_BACK_TAG}"
    container_name: backend_prod
    restart: always
    volumes:
      - static_value:/code/staticfiles/
      - media_value:/code/media/
    depends_on:
      - postgres
    env_file:
      - .env-prod
    networks:
      - prod_db_network
      - swag_network
  migrations:
    image: "${IMAGE_BACK}:${IMAGE_BACK_TAG}"
    container_name: migrations_prod
    volumes:
      - static_value:/code/staticfiles/
      - media_value:/code/media/
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput"
    depends_on:
      - backend
    env_file:
      - .env-prod
    networks:
      - prod_db_network

networks:
  prod_db_network:
    name: prod_db_network
    driver: bridge
  swag_network:
    name: swag_network
    external: true

volumes:
  postgres_data:
    name: postgres_data
  static_value:
    name: static_value
  media_value:
    name: media_value
