version: '3.8'

services:
  frontend_prod:
    image: "${IMAGE_FRONT}:${IMAGE_FRONT_TAG}"
    container_name: frontend_prod
    environment:
      BASE_URL: ${FRONT_BASE_URL}
      API_BASE_URL: ${MASTER_API_BASE_URL}
    networks:
      - swag_network
    ports:
      - "3005:3000"
    restart: always
  
networks:
    swag_network:
      external: true
