version: '3.8'

services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag_prod
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Moscow
      - VALIDATION=http
      - SUBDOMAINS=${DEV_SUBDOMAIN},${TEST_SUBDOMAIN}
      - ONLY_SUBDOMAINS=true
      - CERTPROVIDER=zerossl
    env_file:
      - .env-prod
    networks:
      - swag_network
    volumes:
      - ./swag_config/:/config/
      - ./swag/swag_nginx_prod.conf:/config/nginx/site-confs/default
      - static_value:/config/static/
      - media_value:/config/media/
      - static_value_test:/config/test/static/
      - media_value_test:/config/test/media/
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

networks:
  swag_network:
    name: swag_network
    external: true

volumes:
  static_value:
    name: static_value
    external: true
  media_value:
    name: media_value
    external: true
  static_value_test:
    name: static_value_test
    external: true
  media_value_test:
    name: media_value_test
    external: true
