version: '3.8'

services:
  postgres_test:
    image: postgres:13.3
    container_name: postgres_test
    restart: always
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    env_file:
      - .env-test
    networks:
      - test_db_network
  backend_test:
    image: "${IMAGE}:${IMAGE_TAG}"
    container_name: backend_test
    restart: always
    volumes:
      - static_value_test:/code/staticfiles/
      - media_value_test:/code/media/
    depends_on:
      - postgres_test
    env_file:
      - .env-test
    networks:
      - test_db_network
      - swag_network
  migrations_test:
    image: "${IMAGE}:${IMAGE_TAG}"
    container_name: migrations_test
    volumes:
      - static_value_test:/code/staticfiles/
      - media_value_test:/code/media/
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py createsuperuser --noinput &&
             python manage.py filldb &&
             python manage.py set_perms &&
             python manage.py filldb_articles"
    depends_on:
      - backend_test
    env_file:
      - .env-test
    networks:
      - test_db_network

networks:
    test_db_network:
      name: test_db_network
      driver: bridge
    swag_network:
      name: swag_network
      external: true

volumes:
  postgres_data_test:
    name: postgres_data_test
  static_value_test:
    name: static_value_test
  media_value_test:
    name: media_value_test
