# Generated by Django 3.2.8 on 2021-10-18 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0005_auto_20211017_2001'),
        ('core', '0004_alter_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('image', models.FileField(upload_to='content_images')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ImagesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Блок изображения',
                'verbose_name_plural': 'Блоки изображений',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250, verbose_name='Описание ссылки')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Ссылка с описанием',
                'verbose_name_plural': 'Ссылки с описанием',
            },
        ),
        migrations.CreateModel(
            name='OrderedPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_performances', to='library.performance')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_persons', to='core.person')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_plays', to='library.play')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='VideosBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('videos', models.ManyToManyField(through='content_pages.OrderedVideo', to='content_pages.Video')),
            ],
            options={
                'verbose_name': 'Блок видео',
                'verbose_name_plural': 'Блоки видео',
            },
        ),
        migrations.CreateModel(
            name='PlaysBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('plays', models.ManyToManyField(through='content_pages.OrderedPlay', to='library.Play')),
            ],
            options={
                'verbose_name': 'Блок пьес',
                'verbose_name_plural': 'Блоки пьес',
            },
        ),
        migrations.CreateModel(
            name='PersonsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('persons', models.ManyToManyField(through='content_pages.OrderedPerson', to='core.Person')),
            ],
            options={
                'verbose_name': 'Блок персон',
                'verbose_name_plural': 'Блоки персон',
            },
        ),
        migrations.CreateModel(
            name='PerformancesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('performances', models.ManyToManyField(through='content_pages.OrderedPerformance', to='library.Performance')),
            ],
            options={
                'verbose_name': 'Блок спектаклей',
                'verbose_name_plural': 'Блоки спектаклей',
            },
        ),
        migrations.AddField(
            model_name='orderedvideo',
            name='image_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_videos', to='content_pages.videosblock'),
        ),
        migrations.AddField(
            model_name='orderedvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_videos', to='content_pages.video'),
        ),
        migrations.AddField(
            model_name='orderedplay',
            name='play_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_plays', to='content_pages.playsblock'),
        ),
        migrations.AddField(
            model_name='orderedperson',
            name='person_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_persons', to='content_pages.personsblock'),
        ),
        migrations.AddField(
            model_name='orderedperformance',
            name='performance_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_performances', to='content_pages.performancesblock'),
        ),
        migrations.CreateModel(
            name='OrderedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_images', to='content_pages.image')),
                ('image_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_images', to='content_pages.imagesblock')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='imagesblock',
            name='images',
            field=models.ManyToManyField(through='content_pages.OrderedImage', to='content_pages.Image'),
        ),
    ]
