# Generated by Django 3.2.11 on 2022-01-29 10:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('content_pages', '0001_initial'), ('content_pages', '0002_auto_20211103_0037'), ('content_pages', '0003_alter_text_text'), ('content_pages', '0004_preamble'), ('content_pages', '0005_auto_20211205_1401'), ('content_pages', '0006_alter_extendedperson_options'), ('content_pages', '0007_extendedperson_unique_person_per_block')]

    initial = True

    dependencies = [
        ('core', '0001_initial_squashed_0004_alter_person_image'),
        ('library', '0003_auto_20211013_0054_squashed_0009_alter_author_options'),
        ('core', '0005_settings_squashed_0017_data_add_type_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='content_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='ImagesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Блок изображения',
                'verbose_name_plural': 'Блоки изображений',
            },
        ),
        migrations.CreateModel(
            name='OrderedPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Промежуточная модель %(class)s',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Промежуточная модель %(class)s',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Промежуточная модель %(class)s',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Промежуточная модель %(class)s',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание видео')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='VideosBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('items', models.ManyToManyField(related_name='video_blocks', through='content_pages.OrderedVideo', to='content_pages.Video')),
            ],
            options={
                'verbose_name': 'Блок видео',
                'verbose_name_plural': 'Блоки видео',
            },
        ),
        migrations.CreateModel(
            name='PlaysBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('items', models.ManyToManyField(related_name='play_blocks', through='content_pages.OrderedPlay', to='library.Play')),
            ],
            options={
                'verbose_name': 'Блок пьес',
                'verbose_name_plural': 'Блоки пьес',
            },
        ),
        migrations.CreateModel(
            name='PersonsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('items', models.ManyToManyField(related_name='person_blocks', through='content_pages.OrderedPerson', to='core.Person')),
            ],
            options={
                'verbose_name': 'Блок персон',
                'verbose_name_plural': 'Блоки персон',
            },
        ),
        migrations.CreateModel(
            name='PerformancesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('items', models.ManyToManyField(related_name='performance_blocks', through='content_pages.OrderedPerformance', to='library.Performance')),
            ],
            options={
                'verbose_name': 'Блок спектаклей',
                'verbose_name_plural': 'Блоки спектаклей',
            },
        ),
        migrations.AddField(
            model_name='orderedvideo',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_videos', to='content_pages.videosblock'),
        ),
        migrations.AddField(
            model_name='orderedvideo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_videos', to='content_pages.video'),
        ),
        migrations.AddField(
            model_name='orderedplay',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_plays', to='content_pages.playsblock'),
        ),
        migrations.AddField(
            model_name='orderedplay',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_plays', to='library.play'),
        ),
        migrations.AddField(
            model_name='orderedperson',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_persons', to='content_pages.personsblock'),
        ),
        migrations.AddField(
            model_name='orderedperson',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_persons', to='core.person'),
        ),
        migrations.AddField(
            model_name='orderedperformance',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_performances', to='content_pages.performancesblock'),
        ),
        migrations.AddField(
            model_name='orderedperformance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_performances', to='library.performance'),
        ),
        migrations.CreateModel(
            name='OrderedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_images', to='content_pages.imagesblock')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_images', to='content_pages.image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Содержимое блока',
                'ordering': ('order',),
                'abstract': False,
                'verbose_name_plural': 'Содержимое блоков',
            },
        ),
        migrations.AddField(
            model_name='imagesblock',
            name='items',
            field=models.ManyToManyField(related_name='image_blocks', through='content_pages.OrderedImage', to='content_pages.Image'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField(max_length=500, verbose_name='Цитата')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
            },
        ),
        migrations.AlterModelOptions(
            name='orderedperformance',
            options={'ordering': ('order',), 'verbose_name': 'Содержимое блока', 'verbose_name_plural': 'Содержимое блоков'},
        ),
        migrations.AlterModelOptions(
            name='orderedperson',
            options={'ordering': ('order',), 'verbose_name': 'Содержимое блока', 'verbose_name_plural': 'Содержимое блоков'},
        ),
        migrations.AlterModelOptions(
            name='orderedplay',
            options={'ordering': ('order',), 'verbose_name': 'Содержимое блока', 'verbose_name_plural': 'Содержимое блоков'},
        ),
        migrations.AlterModelOptions(
            name='orderedvideo',
            options={'ordering': ('order',), 'verbose_name': 'Содержимое блока', 'verbose_name_plural': 'Содержимое блоков'},
        ),
        migrations.AlterField(
            model_name='imagesblock',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=250, verbose_name='Описание ссылки')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Ссылка с описанием',
                'verbose_name_plural': 'Ссылки с описанием',
            },
        ),
        migrations.AlterField(
            model_name='orderedperformance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_performances', to='library.performance', verbose_name='Спектакль'),
        ),
        migrations.AlterField(
            model_name='orderedperformance',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.AlterField(
            model_name='orderedperson',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_persons', to='core.person', verbose_name='Персона/человек'),
        ),
        migrations.AlterField(
            model_name='orderedperson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.AlterField(
            model_name='orderedplay',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_plays', to='library.play', verbose_name='Пьеса'),
        ),
        migrations.AlterField(
            model_name='orderedplay',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.AlterField(
            model_name='orderedvideo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_videos', to='content_pages.video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='orderedvideo',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
        migrations.CreateModel(
            name='Preamble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('preamble', models.TextField(max_length=500, verbose_name='Преамбула')),
            ],
            options={
                'verbose_name': 'Преамбула',
                'verbose_name_plural': 'Преамбулы',
            },
        ),
        migrations.AlterField(
            model_name='orderedperson',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_persons', to='content_pages.personsblock', verbose_name='Блок персон'),
        ),
        migrations.CreateModel(
            name='ContentPersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('extended_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_person_roles', to='content_pages.orderedperson', verbose_name='Персона')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_person_roles', to='core.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль у персоны в блоке',
                'verbose_name_plural': 'Роли персон в блоках',
            },
        ),
        migrations.AddField(
            model_name='orderedperson',
            name='roles',
            field=models.ManyToManyField(related_name='ordered_persons', through='content_pages.ContentPersonRole', to='core.Role', verbose_name='Роли персоны'),
        ),
        migrations.AddConstraint(
            model_name='contentpersonrole',
            constraint=models.UniqueConstraint(fields=('extended_person', 'role'), name='unique_role_per_extended_person'),
        ),
        migrations.RenameModel(
            old_name='OrderedPerson',
            new_name='ExtendedPerson',
        ),
        migrations.AlterField(
            model_name='extendedperson',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_persons', to='content_pages.personsblock', verbose_name='Блок персон'),
        ),
        migrations.AlterField(
            model_name='extendedperson',
            name='roles',
            field=models.ManyToManyField(related_name='extended_persons', through='content_pages.ContentPersonRole', to='core.Role', verbose_name='Роли персоны'),
        ),
        migrations.RenameField(
            model_name='extendedperson',
            old_name='item',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='extendedperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_persons', to='core.person', verbose_name='Персона/человек'),
        ),
        migrations.AlterModelOptions(
            name='extendedperson',
            options={'ordering': ('order',), 'verbose_name': 'Элемент блока персон', 'verbose_name_plural': 'Элементы блоков песроны'},
        ),
        migrations.AddConstraint(
            model_name='extendedperson',
            constraint=models.UniqueConstraint(fields=('block', 'person'), name='unique_person_per_block'),
        ),
    ]
