# Generated by Django 3.2.11 on 2022-02-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesblock',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderedimage',
            name='item',
        ),
        migrations.AddField(
            model_name='orderedimage',
            name='image',
            field=models.ImageField(default='content_images/dummy_empty_image.jpg', upload_to='content_images', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderedimage',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок/подпись для картинки. Может быть пустым', max_length=250, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
