# Generated by Django 3.2.8 on 2021-10-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order'], 'verbose_name': 'Элемент сложной верстки', 'verbose_name_plural': 'Элементы сложной верстки'},
        ),
    ]
