# Generated by Django 3.2.7 on 2021-10-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='orderedimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_images', to='content_pages.image'),
        ),
        migrations.AlterField(
            model_name='orderedimage',
            name='image_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_images', to='content_pages.imagesblock'),
        ),
    ]
