# Generated by Django 3.2.8 on 2021-11-03 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_settings_objects'),
        ('library', '0009_alter_author_options'),
        ('content_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('quote', models.TextField(max_length=500, verbose_name='Цитата')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=500, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Заголовок',
                'verbose_name_plural': 'Заголовки',
            },
        ),
        migrations.AlterModelOptions(
            name='orderedimage',
            options={'ordering': ('order',), 'verbose_name': 'Содержимое блока', 'verbose_name_plural': 'Содержимое блоков'},
        ),
        migrations.AlterModelOptions(
            name='orderedperformance',
            options={'ordering': ('order',), 'verbose_name': 'Содержимое блока', 'verbose_name_plural': 'Содержимое блоков'},
        ),
        migrations.AlterModelOptions(
            name='orderedperson',
            options={'ordering': ('order',), 'verbose_name': 'Содержимое блока', 'verbose_name_plural': 'Содержимое блоков'},
        ),
        migrations.AlterModelOptions(
            name='orderedplay',
            options={'ordering': ('order',), 'verbose_name': 'Содержимое блока', 'verbose_name_plural': 'Содержимое блоков'},
        ),
        migrations.AlterModelOptions(
            name='orderedvideo',
            options={'ordering': ('order',), 'verbose_name': 'Содержимое блока', 'verbose_name_plural': 'Содержимое блоков'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='content_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='imagesblock',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='orderedimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_images', to='content_pages.image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='orderedimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.AlterField(
            model_name='orderedperformance',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_performances', to='library.performance', verbose_name='Спектакль'),
        ),
        migrations.AlterField(
            model_name='orderedperformance',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.AlterField(
            model_name='orderedperson',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_persons', to='core.person', verbose_name='Персона/человек'),
        ),
        migrations.AlterField(
            model_name='orderedperson',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.AlterField(
            model_name='orderedplay',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_plays', to='library.play', verbose_name='Пьеса'),
        ),
        migrations.AlterField(
            model_name='orderedplay',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.AlterField(
            model_name='orderedvideo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_videos', to='content_pages.video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='orderedvideo',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке'),
        ),
        migrations.AlterField(
            model_name='performancesblock',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='personsblock',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='playsblock',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='videosblock',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Заголовок'),
        ),
    ]
