# Generated by Django 3.2.8 on 2021-10-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedimage',
            options={'ordering': ['order'], 'verbose_name': 'Промежуточная модель %(class)s'},
        ),
        migrations.AlterModelOptions(
            name='orderedperformance',
            options={'ordering': ['order'], 'verbose_name': 'Промежуточная модель %(class)s'},
        ),
        migrations.AlterModelOptions(
            name='orderedperson',
            options={'ordering': ['order'], 'verbose_name': 'Промежуточная модель %(class)s'},
        ),
        migrations.AlterModelOptions(
            name='orderedplay',
            options={'ordering': ['order'], 'verbose_name': 'Промежуточная модель %(class)s'},
        ),
        migrations.AlterModelOptions(
            name='orderedvideo',
            options={'ordering': ['order'], 'verbose_name': 'Промежуточная модель %(class)s'},
        ),
        migrations.RenameField(
            model_name='imagesblock',
            old_name='images',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='orderedimage',
            old_name='image_block',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='orderedimage',
            old_name='image',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderedperformance',
            old_name='performance_block',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='orderedperformance',
            old_name='performance',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderedperson',
            old_name='person_block',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='orderedperson',
            old_name='person',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderedplay',
            old_name='play_block',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='orderedplay',
            old_name='play',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderedvideo',
            old_name='image_block',
            new_name='block',
        ),
        migrations.RenameField(
            model_name='orderedvideo',
            old_name='video',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='performancesblock',
            old_name='performances',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='personsblock',
            old_name='persons',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='playsblock',
            old_name='plays',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='videosblock',
            old_name='videos',
            new_name='items',
        ),
    ]
