# Generated by Django 3.2.8 on 2021-10-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_auto_20211019_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedvideo',
            old_name='item',
            new_name='some_name',
        ),
    ]
