# Generated by Django 3.2.11 on 2022-02-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_auto_20220207_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedvideo',
            name='item',
        ),
        migrations.RemoveField(
            model_name='videosblock',
            name='items',
        ),
        migrations.AddField(
            model_name='orderedvideo',
            name='title',
            field=models.CharField(blank=True, help_text='Заголовок/подпись для видео. Может быть пустым', max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='orderedvideo',
            name='url',
            field=models.URLField(default='https://some-dummy-url-that-doesnt-exist.ru', verbose_name='Ссылка на видео'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
