# Generated by Django 3.2.11 on 2022-02-07 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_auto_20220207_2058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderedImage',
            new_name='ContentImagesBlockItem',
        ),
    ]
