# Generated by Django 3.2.8 on 2021-10-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20211012_1933'),
        ('content_pages', '0002_alter_content_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='ContentPage',
        ),
    ]
