# Generated by Django 3.2.12 on 2022-02-25 23:42

from django.db import migrations, models

import apps.content_pages.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_auto_20220207_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedimage',
            name='image',
            field=models.ImageField(upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Изображение'),
        ),
    ]
