# Generated by Django 3.2.9 on 2021-11-24 05:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_auto_20211103_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
