# Generated by Django 3.2.7 on 2021-10-03 20:33

from django.db import migrations
import gfklookupwidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_auto_20211002_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='object_id',
            field=gfklookupwidget.fields.GfkLookupField(),
        ),
    ]
