# Generated by Django 3.2.11 on 2022-02-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0002_event_date'),
        ('content_pages', '0002_auto_20220207_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Блок событий',
                'verbose_name_plural': 'Блоки событий',
            },
        ),
        migrations.CreateModel(
            name='OrderedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в блоке')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_events', to='content_pages.eventsblock')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_events', to='afisha.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Содержимое блока',
                'verbose_name_plural': 'Содержимое блоков',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventsblock',
            name='items',
            field=models.ManyToManyField(related_name='events_blocks', through='content_pages.OrderedEvent', to='afisha.Event'),
        ),
    ]
