# Generated by Django 3.2.11 on 2022-02-07 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0003_rename_orderedimage_contentimagesblockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimagesblockitem',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_items', to='content_pages.imagesblock'),
        ),
    ]
