# Generated by Django 3.2.8 on 2021-10-19 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0003_rename_item_orderedvideo_some_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedvideo',
            old_name='some_name',
            new_name='item',
        ),
    ]
