# Generated by Django 3.2.9 on 2021-11-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0003_alter_text_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preamble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('preamble', models.TextField(max_length=500, verbose_name='Преамбула')),
            ],
            options={
                'verbose_name': 'Преамбула',
                'verbose_name_plural': 'Преамбулы',
            },
        ),
    ]
