# Generated by Django 3.2.13 on 2022-05-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0005_contentunitrichtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preamble',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
