# Generated by Django 3.2.10 on 2021-12-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0006_alter_extendedperson_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='extendedperson',
            constraint=models.UniqueConstraint(fields=('block', 'person'), name='unique_person_per_block'),
        ),
    ]
