# Generated by Django 3.2.13 on 2022-07-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0006_auto_20220531_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsblock',
            options={'verbose_name': 'Блок событий', 'verbose_name_plural': 'Блоки событий'},
        ),
    ]
