# Generated by Django 3.2.20 on 2023-09-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0007_alter_eventsblock_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendedperson',
            options={'ordering': ('order',), 'verbose_name': 'Элемент блока персон', 'verbose_name_plural': 'Элементы блоков персоны'},
        ),
    ]
