# Generated by Django 3.2.7 on 2021-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210928_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
