# Generated by Django 3.2.7 on 2021-10-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Festival_settings', 'Настройки фестиваля'), ('Main_page_settings', 'Настройки главной страницы'), ('History_page_settings', 'Настройки страницы истории'), ('About_festival_what_we_do_page_settings', 'Настройки страницы О фестивале. Что мы делаем?'), ('About_festival_ideology_page_settings', 'Настройки страницы О фестивале. Идеология.'), ('Other_settings', 'Прочие настройки')], max_length=40, verbose_name='Выбор типа настроек')),
                ('field_type', models.CharField(choices=[('boolean', 'Да/Нет'), ('title', 'Заголовок/Описание'), ('text', 'Текст'), ('url', 'URL'), ('image', 'Картинка')], max_length=40, verbose_name='Выбор поля настроек')),
                ('settings_key', models.SlugField(max_length=40, unique=True, verbose_name='Ключ настроек')),
                ('boolean', models.BooleanField(default=False, verbose_name='Да или Нет')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=100, verbose_name='Текст')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, upload_to='core/', verbose_name='Изображение')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
                'ordering': ['id'],
            },
        ),
    ]
