# Generated by Django 3.2.7 on 2021-10-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingImageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_order', models.PositiveIntegerField(verbose_name='Порядковый номер картинки на странице сверху вниз')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_blocks', to='core.image', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['image_order'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Festival_settings', 'Настройки фестиваля'), ('Main_page_settings', 'Настройки главной страницы'), ('History_page_settings', 'Настройки страницы истории'), ('About_festival_what_we_do_page_settings', 'Настройки страницы О фестивале. Что мы делаем?'), ('About_festival_ideology_page_settings', 'Настройки страницы О фестивале. Идеология.'), ('Other_settings', 'Прочие настройки')], max_length=40, verbose_name='Выбор типа настроек')),
                ('field_type', models.CharField(choices=[('boolean', 'Да/Нет'), ('title', 'Заголовок/Описание'), ('text', 'Текст'), ('url', 'URL'), ('image', 'Картинка'), ('block', 'Блок для страницы')], max_length=40, verbose_name='Выбор поля настроек')),
                ('settings_key', models.SlugField(max_length=40, unique=True, verbose_name='Ключ настроек')),
                ('boolean', models.BooleanField(default=False, verbose_name='Да или Нет')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=100, verbose_name='Текст')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, upload_to='core/', verbose_name='Изображение')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('images_for_page', models.ManyToManyField(blank=True, related_name='images', through='core.SettingImageRelation', to='core.Image', verbose_name='Картинки для страницы')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='settingimagerelation',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.settings', verbose_name='Настройка'),
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(blank=True, max_length=100, verbose_name='Описание или заголовок блока')),
                ('block_text', models.TextField(max_length=300, verbose_name='Текст блока')),
                ('block', models.CharField(choices=[('Main', 'Главный блок'), ('First', 'Первая группа блоков, относящаяся к первому подзаголовку'), ('Second', 'Вторая группа блоков, относящаяся к первому подзаголовку')], max_length=30, verbose_name='Принадлежность к блоку')),
                ('block_order', models.PositiveIntegerField(verbose_name='Порядок отображения внутри блоков странице сверху вниз')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.settings')),
            ],
            options={
                'verbose_name': 'Информационный блок',
                'verbose_name_plural': 'Информационные блоки',
                'ordering': ['block_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='settingimagerelation',
            constraint=models.UniqueConstraint(fields=('settings', 'image_order'), name='unique_image_order'),
        ),
        migrations.AddConstraint(
            model_name='infoblock',
            constraint=models.UniqueConstraint(fields=('setting', 'block', 'block_order'), name='unique_order'),
        ),
    ]
