# Generated by Django 3.2.7 on 2021-10-27 09:45

from django.db import migrations


def add_settings(apps, schema_editor):

    Settings = apps.get_model('core', 'Settings')
    Settings.objects.create(
        field_type="BOOLEAN",
        settings_key="Festival_status",
        boolean=True,
    )
    Settings.objects.create(
        field_type="TEXT",
        settings_key="Site_color",
        text="green",
    )
    Settings.objects.create(
        field_type="EMAIL",
        settings_key="Mail_send_to",
        email="testtest@testtest.test",
    )
    Settings.objects.create(
        field_type="BOOLEAN",
        settings_key="Form_to_submit_a_play",
        boolean=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_settings'),
    ]

    operations = [
        migrations.RunPython(add_settings),
    ]
