# Generated by Django 3.2.7 on 2021-10-27 09:45

from django.db import migrations


def add_settings(apps, schema_editor):

    Settings = apps.get_model('core', 'Settings')
    Settings.objects.create(
        field_type="BOOLEAN",
        settings_key="festival_status",
        boolean=True,
    )
    Settings.objects.create(
        field_type="TEXT",
        settings_key="site_color",
        text="green",
    )
    Settings.objects.create(
        field_type="EMAIL",
        settings_key="mail_send_to",
        email="testtest@testtest.test",
    )
    Settings.objects.create(
        field_type="BOOLEAN",
        settings_key="form_to_submit_a_play",
        boolean=True,
    )
    Settings.objects.create(
        field_type="TEXT",
        settings_key="email_subject_for_question",
        text="Вопрос Любимовке",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_settings'),
    ]

    operations = [
        migrations.RunPython(add_settings),
    ]
