# Generated by Django 3.2.9 on 2021-11-03 19:23

from django.db import migrations


def add_settings(apps, schema_editor):
    Settings = apps.get_model('core', 'Settings')
    values = [
        "Festival_status",
        "Site_color",
        "Mail_send_to",
        "Form_to_submit_a_play"
    ]
    for value in values:
        if Settings.objects.filter(
            settings_key=value,
        ).exists():
            setting = Settings.objects.get(settings_key=value,)
            setting.settings_key = value.lower()
            setting.save()

    Settings.objects.get_or_create(
        field_type="TEXT",
        settings_key="email_subject_for_question",
        text="Вопрос Любимовке",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_create_settings_objects'),
    ]

    operations = [
        migrations.RunPython(add_settings),
    ]
