# Generated by Django 3.2.11 on 2022-02-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_emails_on_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='group',
            field=models.CharField(choices=[('EMAIL', 'Почта'), ('MAIN', 'Главная'), ('FIRST_SCREEN', 'Первая страница'), ('GENERAL', 'Общие'), ('AFISHA', 'Афиша'), ('GOOGLE_EXPORT', 'Экспорт в GOOGLE таблицу')], default='GENERAL', max_length=50, verbose_name='Группа настроек'),
        ),
    ]
