# Generated by Django 3.2.11 on 2022-02-06 12:56

from django.db import migrations


def change_first_screen_settings(apps, schema_editor):

    Setting = apps.get_model("core", "Setting")

    # changing main_first_screen_url_title
    setting, _ = Setting.objects.get_or_create(
        field_type="TEXT",
        group="FIRST_SCREEN",
        settings_key="main_first_screen_url_title",
    )
    setting.description = "Заголовок для ссылки для первой страницы"
    setting.save()

    # changing main_first_screen_url
    setting, _ = Setting.objects.get_or_create(
        field_type="URL",
        group="FIRST_SCREEN",
        settings_key="main_first_screen_url",
    )
    setting.description = "Ссылка для первой страницы"
    setting.save()

def change_main_settings(apps, schema_editor):

    Setting = apps.get_model("core", "Setting")

    # changing main_add_afisha
    setting, _ = Setting.objects.get_or_create(
        field_type="BOOLEAN",
        group="MAIN",
        settings_key="main_add_afisha",
    )
    setting.description = "Отображение афиши на главной странице"
    setting.save()

    # changing main_add_banners
    setting, _ = Setting.objects.get_or_create(
        field_type="BOOLEAN",
        group="MAIN",
        settings_key="main_add_banners",
    )
    setting.description = "Отображение банера на главной странице"
    setting.save()

    # changing main_add_blog
    setting, _ = Setting.objects.get_or_create(
        field_type="BOOLEAN",
        group="MAIN",
        settings_key="main_add_blog",
    )
    setting.description = "Отображение дневника на главной странице"
    setting.save()

    # changing main_add_news
    setting, _ = Setting.objects.get_or_create(
        field_type="BOOLEAN",
        group="MAIN",
        settings_key="main_add_news",
    )
    setting.description = "Отображение новостей на главной странице"
    setting.save()

    # changing main_add_places
    setting, _ = Setting.objects.get_or_create(
        field_type="BOOLEAN",
        group="MAIN",
        settings_key="main_add_places",
    )
    setting.description = "Отображение площадок на главной странице"
    setting.save()

    # changing main_add_short_list
    setting, _ = Setting.objects.get_or_create(
        field_type="BOOLEAN",
        group="MAIN",
        settings_key="main_add_short_list",
    )
    setting.description = "Отображение шорт-листа на главной странице"
    setting.save()

    # changing main_add_video_archive
    setting, _ = Setting.objects.get_or_create(
        field_type="BOOLEAN",
        group="MAIN",
        settings_key="main_add_video_archive",
        boolean=True,
    )
    setting.description = "Отображение видео-архива на главной странице"
    setting.save()

    # changing main_blog_title
    setting, _ = Setting.objects.get_or_create(
        field_type="TEXT",
        group="MAIN",
        settings_key="main_blog_title",
    )
    setting.description = "Заголовок для дневника на главной странице"
    setting.save()

    # changing main_news_title
    setting, _ = Setting.objects.get_or_create(
        field_type="TEXT",
        group="MAIN",
        settings_key="main_news_title",
    )
    setting.description = "Заголовок для новостей на главной странице"
    setting.save()

    # changing main_short_list_title
    setting, _ = Setting.objects.get_or_create(
        field_type="TEXT",
        group="MAIN",
        settings_key="main_short_list_title",
    )
    setting.description = "Заголовок для шорт-листа на главной странице"
    setting.save()

    # changing main_video_archive_photo
    setting, _ = Setting.objects.get_or_create(
        field_type="IMAGE",
        group="MAIN",
        settings_key="main_video_archive_photo",
    )
    setting.description = "Фото для видео-архива на главной странице"
    setting.save()

    # changing main_video_archive_url
    setting, _ = Setting.objects.get_or_create(
        field_type="URL",
        group="MAIN",
        settings_key="main_video_archive_url",
    )
    setting.description = "Ссылка на youtube видео-архива на главной странице"
    setting.save()


def change_afisha_settings(apps, schema_editor):

    Setting = apps.get_model("core", "Setting")

    # adding afisha_description
    Setting.objects.get_or_create(
        field_type="TEXT",
        group="AFISHA",
        settings_key="afisha_description",
        text="На все читки и мастер-классы фестиваля вход свободный по предварительной регистрации.",
        description="Описание под заголовком",
    )

    # removing afisha_title_regular
    Setting.objects.filter(
        field_type="TEXT",
        group="AFISHA",
        settings_key="afisha_title_regular",
    ).delete()

    # removing afisha_title_festival
    Setting.objects.filter(
        field_type="TEXT",
        group="AFISHA",
        settings_key="afisha_title_festival",
    ).delete()

    # removing afisha_description_festival
    Setting.objects.filter(
        field_type="TEXT",
        group="AFISHA",
        settings_key="afisha_description_festival",
    ).delete()

    # removing afisha_description_regular
    Setting.objects.filter(
        field_type="TEXT",
        group="AFISHA",
        settings_key="afisha_description_regular",
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_emails_on_settings'),
    ]

    operations = [
        migrations.RunPython(
            change_first_screen_settings,
        ),
        migrations.RunPython(
            change_main_settings,
        ),
        migrations.RunPython(
            change_afisha_settings,
        ),
    ]
