# Generated by Django 3.2.9 on 2021-11-03 19:23

from django.db import migrations


def add_description(apps, schema_editor):
    Setting = apps.get_model('core', 'Setting')
    description_values = {
        "festival_status": "Статус фестиваля",
        "site_color": "Цвет сайта",
        "mail_send_to": "Почта для отправки сообщений",
        "form_to_submit_a_play": "Форма для отправки пьесы",
        "email_subject_for_question": "Тема письма для вопроса"
    }
    for key, value in description_values.items():
        if Setting.objects.filter(
            settings_key=key,
        ).exists():
            setting = Setting.objects.get(settings_key=key,)
            setting.description = value
            setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211118_1714'),
    ]

    operations = [
        migrations.RunPython(add_description),
    ]
