# Generated by Django 3.2.9 on 2021-11-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('name_plural', models.CharField(max_length=50, unique=True, verbose_name='Название во множественном числе')),
                ('slug', models.SlugField(help_text='Если пустое, то заполняется автоматически', max_length=60, unique=True, verbose_name='Код-имя латиницей')),
            ],
            options={
                'verbose_name': 'Должность/позиция',
                'verbose_name_plural': 'Должности/позиции',
                'ordering': ('name',),
            },
        ),
    ]
