# Generated by Django 3.2.9 on 2021-11-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.CharField(max_length=60, verbose_name='Описание настройки'),
        ),
    ]
