# Generated by Django 3.2.12 on 2022-02-20 19:05

from django.db import migrations, models


def set_status(apps, schema_editor):
    Status = apps.get_model("core", "Status")
    Status.objects.create(
        name="В работе",
        button_name="Вернуть в работу",
    )
    Status.objects.create(
        name="На проверке",
        button_name="Отправить на проверку",
    )
    Status.objects.create(
        name="Готово к публикации",
        button_name="Подготовить к публикации",
    )
    Status.objects.create(
        name="Опубликовано",
        button_name="Опубликовать",
        protected=True,
    )
    Status.objects.create(
        name="Снято с публикации",
        button_name="Снять с публикации",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_setting_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Наименование')),
                ('button_name', models.CharField(blank=True, max_length=55, null=True, verbose_name='Название кнопки для статуса')),
                ('protected', models.BooleanField(default=False, verbose_name='Требуются особые права для установки данного статуса')),
            ],
            options={
                'verbose_name': 'Статус страницы',
                'verbose_name_plural': 'Статусы страницы',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Загрузите фотографию', upload_to='images/core/', verbose_name='Изображение'),
        ),
        migrations.RunPython(
            set_status,
        )
    ]
