# Generated by Django 3.2.9 on 2021-11-23 22:38

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    roles = [
        {
            "name": "Актёр",
            "name_plural": "Актёры",
            "slug": "actor",
        },
        {
            "name": "Адаптация текста",
            "name_plural": "Адаптация текста",
            "slug": "text_adaptation",
        },
        {
            "name": "Драматург",
            "name_plural": "Драматурги",
            "slug": "dramatist",
        },
        {
            "name": "Режиссёр",
            "name_plural": "Режиссёры",
            "slug": "director",
        },
        {
            "name": "Переводчик",
            "name_plural": "Переводчики",
            "slug": "translator",
        },
        {
            "name": "Ведущий",
            "name_plural": "Ведущие",
            "slug": "host",
        },
        {
            "name": "Текст",
            "name_plural": "Текст",
            "slug": "text",
        },
        {
            "name": "Иллюстрации",
            "name_plural": "Иллюстрации",
            "slug": "illustrations",
        },
        {
            "name": "Фото",
            "name_plural": "Фото",
            "slug": "photo",
        },
    ]
    for role in roles:
        role_obj, _ = Role.objects.get_or_create(**role)
        role_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_role"),
    ]

    operations = [migrations.RunPython(create_roles)]
