# Generated by Django 3.2.9 on 2021-11-20 23:23
from collections import namedtuple

from django.db import migrations


def create_roles(apps, schema_editor):
    RoleModel = apps.get_model('core', 'Role')
    Role = namedtuple('Role', 'name slug')
    roles = [
        Role('Актёр', 'actor'),
        Role('Адаптация текста', 'text_adaptation'),
        Role('Драматург', 'dramatist'),
        Role('Режиссёр', 'director'),
        Role('Переводчик', 'transkator'),
        Role('Ведущий', 'host')
    ]
    for role in roles:
        role_obj, _ = RoleModel.objects.get_or_create(
            name=role.name, slug=role.slug
        )
        role_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_role'),
    ]

    operations = [
        migrations.RunPython(create_roles)
    ]
