# Generated by Django 3.2.12 on 2022-02-25 23:42

import apps.content_pages.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_press_release_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(help_text='Загрузите фотографию', upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Изображение'),
        ),
    ]
