# Generated by Django 3.2.9 on 2021-11-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_data_initial_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(max_length=250, null=True, verbose_name='Описание настройки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='Текст'),
        ),
    ]
