# Generated by Django 3.2.9 on 2021-11-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_data_initial_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='news_item',
            field=models.BooleanField(default=False, verbose_name='блок Новостей'),
        ),
        migrations.AddField(
            model_name='settings',
            name='partners',
            field=models.BooleanField(default=False, verbose_name='блок Партнеров'),
        ),
        migrations.AddField(
            model_name='settings',
            name='performances',
            field=models.BooleanField(default=False, verbose_name='блок Спектаклей'),
        ),
        migrations.AddField(
            model_name='settings',
            name='places',
            field=models.BooleanField(default=False, verbose_name='блок Площадок'),
        ),
        migrations.AddField(
            model_name='settings',
            name='readings',
            field=models.BooleanField(default=False, verbose_name='блок Читки/Пьесы'),
        ),
        migrations.AddField(
            model_name='settings',
            name='sponsors',
            field=models.BooleanField(default=False, verbose_name='блок Спонсоров'),
        ),
    ]
