# Generated by Django 3.2.12 on 2022-02-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220226_0242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
