# Generated by Django 3.2.9 on 2021-11-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_data_add_main_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='type_roles',
            field=models.CharField(choices=[('blog_persons_roles', 'Роли в блоге'), ('performanse_roles', 'Роли в спектаклях'), ('play_roles', 'Роли в пьесах')], default='blog_persons_roles', help_text='Укажите, где будет использована роль', max_length=20, verbose_name='Тип роли'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('name', 'type_roles'), name='unique_roles'),
        ),
    ]
