# Generated by Django 3.2.9 on 2021-12-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_data_add_main_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingOne',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.settings',),
        ),
        migrations.AddField(
            model_name='settings',
            name='settings_group',
            field=models.CharField(choices=[('MAIL', 'Mail'), ('MAIN', (('AFISHA', 'Afisha'), ('NEWS', 'News')))], default='MAIL', max_length=50),
        ),
    ]
