# Generated by Django 3.2.9 on 2021-12-03 22:03

from django.db import migrations


def add_missing_settings(apps, schema_editor):
    """Delete this if you merging migrations.

    These settings have been added to 0013 migration already. If you in
    a process of merging megrations please just delete this one.
    """

    Settings = apps.get_model("core", "Settings")
    Settings.objects.get_or_create(
        field_type="TEXT",
        settings_key="main_afisha_description",
        text="",
        description="На все читки и мастер-классы фестиваля вход свободный по предварительной регистрации.",
    )
    Settings.objects.get_or_create(
        field_type="TEXT",
        settings_key="main_afisha_button_label",
        text="Полная афиша",
        description="Ярлык ссылки на странице афиши",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_data_add_main_settings"),
    ]

    operations = [
        migrations.RunPython(add_missing_settings),
    ]
