# Generated by Django 3.2.9 on 2021-12-04 15:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_data_add_main_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsEmail',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки почты',
                'verbose_name_plural': 'Настройки почты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.settings',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SettingsFirstScreen',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки первой страницы',
                'verbose_name_plural': 'Настройки первой страницы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.settings',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SettingsGeneral',
            fields=[
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.settings',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SettingsMain',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.settings',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ('group', 'settings_key'), 'verbose_name': 'Общие настройки', 'verbose_name_plural': 'Общие настройки'},
        ),
        migrations.AddField(
            model_name='settings',
            name='group',
            field=models.CharField(choices=[('EMAIL', 'Почта'), ('MAIN', 'Главная'), ('FIRST_SCREEN', 'Первая страница'), ('GENERAL', 'Общие')], default='GENERAL', max_length=50, verbose_name='Группа настроек'),
        ),
    ]
