# Generated by Django 3.2.9 on 2021-12-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_data_add_missing_main_settings'),
    ]

    operations = [
        migrations.RenameModel('Settings', 'Setting'),
        migrations.CreateModel(
            name='SettingEmail',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки почты',
                'verbose_name_plural': 'Настройки почты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.setting',),
        ),
        migrations.CreateModel(
            name='SettingFirstScreen',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки первой страницы',
                'verbose_name_plural': 'Настройки первой страницы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.setting',),
        ),
        migrations.CreateModel(
            name='SettingGeneral',
            fields=[
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.setting',),
        ),
        migrations.CreateModel(
            name='SettingMain',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.setting',),
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ('group', 'settings_key'), 'verbose_name': 'Общие настройки', 'verbose_name_plural': 'Общие настройки'},
        ),
        migrations.AddField(
            model_name='setting',
            name='group',
            field=models.CharField(choices=[('EMAIL', 'Почта'), ('MAIN', 'Главная'), ('FIRST_SCREEN', 'Первая страница'), ('GENERAL', 'Общие')], default='GENERAL', max_length=50, verbose_name='Группа настроек'),
        ),
    ]
