# Generated by Django 3.2.9 on 2021-12-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211130_2202'),
        ('core', '0014_data_add_missing_main_settings'),
    ]

    operations = [
    ]
