# Generated by Django 3.2.9 on 2021-12-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20211202_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SettingOne',
        ),
        migrations.CreateModel(
            name='SettingsFirstScreen',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки первой страницы',
                'verbose_name_plural': 'Настройки первой страницы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.settings',),
        ),
        migrations.CreateModel(
            name='SettingsGeneral',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки общие',
                'verbose_name_plural': 'Настройки общие',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.settings',),
        ),
        migrations.CreateModel(
            name='SettingsMail',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки почты',
                'verbose_name_plural': 'Настройки почты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.settings',),
        ),
        migrations.CreateModel(
            name='SettingsMain',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки главной страницы',
                'verbose_name_plural': 'Настройки главной страницы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.settings',),
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ('settings_group',), 'verbose_name': 'Общие настройки', 'verbose_name_plural': 'Общие настройки'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='settings_group',
            field=models.CharField(choices=[('MAIL', 'Почта'), ('MAIN', 'Главная'), ('FIRST_SCREEN', 'Первая страница'), ('GENERAL', 'Общие')], default='MAIL', max_length=50),
        ),
    ]
