# Generated by Django 3.2.9 on 2021-12-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_data_add_missing_main_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250, verbose_name='Описание настройки'),
            preserve_default=False,
        ),
    ]
