# Generated by Django 3.2.9 on 2021-12-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20211204_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('blog_persons_role', 'Роль в блоге'), ('performanse_role', 'Роль в спектаклях'), ('play_role', 'Роль в пьесах'), ('master_class_role', 'Роль в мастер классах'), ('reading_role', 'Роль в читках')], default='blog_persons_role', help_text='Укажите, где будет использована роль', max_length=20, unique=True, verbose_name='Тип роли')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='unique_roles',
        ),
        migrations.RemoveField(
            model_name='role',
            name='type_roles',
        ),
        migrations.AddField(
            model_name='role',
            name='type_roles',
            field=models.ManyToManyField(related_name='type_roles', to='core.RoleType', verbose_name='Типы ролей'),
        ),
    ]
