# Generated by Django 3.2.13 on 2022-05-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_data_additional_and_updated_email_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text='Поле не обязательное', max_length=200, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
