# Generated by Django 3.2.13 on 2022-06-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_data_update_show_afisha_for_today_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text='Поле обязательно для членов команды', max_length=200, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
