# Generated by Django 3.2.13 on 2022-06-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_data_new_email_to_send_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='Электронная почта'),
        ),
    ]
