# Generated by Django 3.2.10 on 2021-12-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_setting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='json',
            field=models.JSONField(blank=True, default=dict, help_text='Настройки указываются в формате: {"поле": "значение", "поле": "значение"}', max_length=500, verbose_name='Json'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='field_type',
            field=models.CharField(choices=[('BOOLEAN', 'Да/Нет'), ('TEXT', 'Текст'), ('URL', 'URL'), ('IMAGE', 'Картинка'), ('EMAIL', 'EMAIL'), ('BANNER', 'BANNER'), ('JSON', 'JSON')], max_length=40, verbose_name='Выбор поля настроек'),
        ),
    ]
