# Generated by Django 3.2.10 on 2022-01-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_create_settings_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='json',
            field=models.JSONField(blank=True, verbose_name='Json'),
        ),
    ]
