# Generated by Django 3.2.10 on 2022-01-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_data_add_type_roles_another'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='json',
            field=models.JSONField(blank=True, default=dict, verbose_name='Json'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='setting',
            name='field_type',
            field=models.CharField(choices=[('BOOLEAN', 'Да/Нет'), ('TEXT', 'Текст'), ('URL', 'URL'), ('IMAGE', 'Картинка'), ('EMAIL', 'EMAIL'), ('BANNER', 'BANNER'), ('JSON', 'JSON')], max_length=40, verbose_name='Выбор поля настроек'),
        ),
    ]
