# Generated by Django 3.2.13 on 2022-07-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_person_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(help_text='Заполняется автоматически', max_length=60, unique=True, verbose_name='Код-имя латиницей'),
        ),
    ]
