# Generated by Django 3.2.10 on 2022-01-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_data_add_type_roles_another'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='group',
            field=models.CharField(choices=[('EMAIL', 'Почта'), ('MAIN', 'Главная'), ('FIRST_SCREEN', 'Первая страница'), ('GENERAL', 'Общие'), ('AFISHA', 'Афиша')], default='GENERAL', max_length=50, verbose_name='Группа настроек'),
        ),
    ]
