# Generated by Django 3.2.13 on 2022-08-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_data_setting_block_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город проживания'),
        ),
    ]
