# Generated by Django 3.2.13 on 2022-09-05 12:50

from django.db import migrations, models


def reorder(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    for order, item in enumerate(Role.objects.all().order_by("name"), 1):
        item.priority = order
        item.save(update_fields=['priority'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20220811_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('priority',), 'verbose_name': 'Должность/позиция', 'verbose_name_plural': 'Должности/позиции'},
        ),
        migrations.AddField(
            model_name='role',
            name='priority',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Определяет очередность вывода (1 - самый важный)', verbose_name='Место по важности'),
        ),
        migrations.RunPython(reorder, reverse_code=migrations.RunPython.noop),
    ]
