# Generated by Django 3.2.13 on 2022-09-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20220905_1550'),
        ('core', '0030_rename_email_settings'),
    ]

    operations = [
    ]
