# Generated by Django 3.2.11 on 2022-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_image_main_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, help_text='Обязательно указать для: членов команды, попечителей фестиваля и волонтёров.', upload_to='images/person_avatars', verbose_name='Фотография'),
        ),
    ]
