# Generated by Django 3.2.16 on 2023-02-07 18:03

from django.db import migrations


def add_settings(apps, schema_editor):
    Setting = apps.get_model("core", "Setting")

    Setting.objects.create(
        field_type="TEXT",
        group="AFISHA",
        settings_key="afisha_registration_opens_days_before",
        text="1",
        description="За сколько дней до мероприятия открывается регистрация",
    )

    Setting.objects.create(
        field_type="TEXT",
        group="AFISHA",
        settings_key="afisha_registration_open_hour",
        text="12",
        description="В котором часу открывается регистрация",
    )


def remove_settings(apps, schema_editor):
    Setting = apps.get_model("core", "Setting")
    Setting.objects.filter(settings_key="afisha_registration_opens_days_before").delete()
    Setting.objects.filter(settings_key="afisha_registration_open_hour").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_email_settings'),
    ]

    operations = [
        migrations.RunPython(add_settings, remove_settings),
    ]
