# Generated by Django 3.2.18 on 2023-05-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_update_questions_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roletype',
            name='role_type',
            field=models.CharField(choices=[('blog_persons_role', 'Роль в блоге'), ('performanse_role', 'Роль в спектаклях'), ('play_role', 'Роль в пьесах'), ('reading_role', 'Роль в читках')], default='blog_persons_role', help_text='Укажите, где будет использована роль', max_length=20, unique=True, verbose_name='Тип роли'),
        ),
    ]
