# Generated by Django 3.2.23 on 2024-01-12 14:56

from django.db import migrations
from django.db.models import Q


def get_admin_group(apps):
    return apps.get_model("auth", "Group").objects.get(name="admin")


def get_permissions(apps):
    return apps.get_model("auth", "Permission").objects.filter(Q(codename__endswith="_virtual") | Q(codename__endswith="_recipient"))


def add_permissions(apps, schema_editor):
    get_admin_group(apps).permissions.add(*get_permissions(apps).values_list("pk", flat=True))


def remove_permissions(apps, schema_editor):
    get_admin_group(apps).permissions.remove(*get_permissions(apps).values_list("pk", flat=True))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_show_page_settings'),
    ]

    operations = [
        migrations.RunPython(add_permissions, remove_permissions),
    ]
