# Generated by Django 3.2.23 on 2024-01-25 14:15

from django.db import migrations

YANDEX_UPLOAD_SETTING = "yandex_upload"

def add_settings(apps, schema_editor):
    Setting = apps.get_model("core", "Setting")
    Setting.objects.get_or_create(
        field_type="BOOLEAN",
        group="PLAY_SUPPLY",
        settings_key=YANDEX_UPLOAD_SETTING,
        boolean=True,
        description="Загружать копию на Яндекс.Диск",
    )


def remove_settings(apps, schema_editor):
    Setting = apps.get_model("core", "Setting")
    Setting.objects.filter(settings_key__in=(YANDEX_UPLOAD_SETTING,)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_add_mail_permissions'),
    ]

    operations = [
        migrations.RunPython(add_settings, remove_settings),
    ]
