# Generated by Django 3.2.25 on 2024-05-11 23:05

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_yandex_disk_setting'),
    ]

    operations = [
        UnaccentExtension(),
    ]
