# Generated by Django 3.2.23 on 2024-04-20 13:08

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_yandex_disk_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text='Необходим, если для связанного автора создан виртуальный адрес', max_length=200, null=True, unique=True, validators=[apps.core.validators.email_validator], verbose_name='Электронная почта'),
        ),
    ]
