# Generated by Django 3.2.25 on 2024-05-21 23:10

from django.db import migrations, models

TEMPLATE = "<a href=\"https://docs.google.com/spreadsheets/d/{0}/\">{0}</a>"


def add_google_sheet_url_template(apps, schema_editor):
    Setting = apps.get_model("core", "Setting")
    Setting.objects.filter(settings_key="SPREADSHEET_ID").update(html_template=TEMPLATE)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_unaccent'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='html_template',
            field=models.CharField(default='', max_length=128, verbose_name='Шаблон для вывода значения'),
        ),
        migrations.RunPython(add_google_sheet_url_template, migrations.RunPython.noop)
    ]
