# Generated by Django 3.2.13 on 2022-07-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_participationapplicationfestival_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationapplicationfestival',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='participationapplicationfestival',
            name='sent_to_email',
            field=models.BooleanField(default=False, editable=False, verbose_name='Подтверждение отправлено'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sent_to_email',
            field=models.BooleanField(default=False, editable=False, verbose_name='Подтверждение отправлено'),
        ),
    ]
