# Generated by Django 3.2.16 on 2023-02-21 20:17
import re

import yadisk
from django.db import migrations
from django.conf import settings

from apps.feedback.services.yandex_disk_export import publish_file

FILENAME_RE = re.compile(r"&filename=(.+?)&")


def fix_links(apps, schema_editor):
    yndx = yadisk.YaDisk(token=settings.YNDX_DISK_TOKEN)
    Application = apps.get_model('feedback', 'ParticipationApplicationFestival')
    for application in Application.objects.filter(url_file_in_storage__contains="downloader.disk.yandex.ru"):
        name = FILENAME_RE.search(application.url_file_in_storage).groups()[0]
        if not name:
            continue
        year = application.festival_year
        path = f"{year}/{name}"
        url = publish_file(yndx, path)
        if not url:
            continue
        application.url_file_in_storage = url
        application.save()


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20220720_1135'),
    ]

    operations = [
        migrations.RunPython(fix_links, reverse_code=migrations.RunPython.noop),
    ]
