# Generated by Django 3.2.21 on 2023-11-10 18:11

import apps.feedback.utilities
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_fix_existing_yandex_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationapplicationfestival',
            name='file',
            field=models.FileField(blank=True, help_text="Файл должен быть в одном из поддерживаемых форматов: ('doc', 'docx', 'txt', 'odt', 'pdf')", max_length=350, upload_to=apps.feedback.utilities.generate_upload_path, validators=[django.core.validators.FileExtensionValidator(('doc', 'docx', 'txt', 'odt', 'pdf'))], verbose_name='Файл'),
        ),
    ]
