# Generated by Django 3.2.23 on 2024-01-26 15:24

from django.conf import settings
from django.db import migrations
from shutil import copytree, move

REGULAR_MEDIA = settings.MEDIA_ROOT / "plays"
PROTECTED_MEDIA = settings.PRIVATE_STORAGE_ROOT / "plays"


def move_to_protected_media(apps, schema_editor):
    copytree(REGULAR_MEDIA, PROTECTED_MEDIA, copy_function=move, dirs_exist_ok=True)


def move_from_protected_media(apps, schema_editor):
    copytree(PROTECTED_MEDIA, REGULAR_MEDIA, copy_function=move, dirs_exist_ok=True)


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_question_created'),
    ]

    operations = [
        migrations.RunPython(move_to_protected_media, move_from_protected_media),
    ]
