# Generated by Django 3.2.25 on 2024-04-26 21:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_participationapplicationfestival_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participationapplicationfestival',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='participationapplicationfestival',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Номер телефона указывается в формате +7', max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
