# Generated by Django 3.2.25 on 2024-05-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20240427_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationapplicationfestival',
            name='anonym',
            field=models.BooleanField(default=False, verbose_name='Анонимность'),
        ),
    ]
