# Generated by Django 3.2.7 on 2021-09-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Редактор', 'Редактор'), ('Администратор', 'Администратор')], default='Редактор', max_length=13, verbose_name='Роль'),
        ),
    ]
