# Generated by Django 3.2.12 on 2022-04-10 22:19

from django.db import migrations, models

def set_email(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if not user.email:
            user.email = f"{user.id}_{user.first_name}_{user.last_name}@here_should_be_real_email.ru"
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_proxygroup'),
    ]

    operations = [
        migrations.RunPython(
            set_email,
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
