# Generated by Django 3.2.12 on 2022-04-04 10:13

from django.db import migrations


def sites_sessions_delete(apps, schema_editor):
    # removing user_permissions for apps sessions and sites
    Permission = apps.get_model('auth', 'Permission')

    Permission.objects.filter(
        content_type__app_label__startswith='s'
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_proxygroup'),
    ]

    operations = [
        migrations.RunPython(
            sites_sessions_delete,
        ),
    ]
