# Generated by Django 3.2.13 on 2022-06-28 20:50

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220411_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[apps.core.validators.email_validator], verbose_name='Электронная почта'),
        ),
    ]
