version: '3.8'

services:
  swag:
    image: linuxserver/swag:1.26.0
    container_name: swag_prod
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Moscow
      - VALIDATION=http
      - EXTRA_DOMAINS=2022.lubimovka.ru
    env_file:
      - .env-prod
    networks:
      - prod_swag_network
    volumes:
      - ./swag/swag_nginx_prod.conf:/config/nginx/site-confs/default
      - swag_volume_prod:/config
      - ./logs/swag_logs/:/config/log/
      - static_value_prod:/config/prod/static/
      - ./media:/config/prod/media/
      - ./protected_media:/config/prod/protected_media/
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
  frontend_prod:
    image: "${IMAGE_FRONT}:${IMAGE_FRONT_TAG}"
    container_name: frontend_prod
    environment:
      BASE_URL: ${FRONT_BASE_URL}
      API_BASE_URL: ${API_BASE_URL}
    networks:
      - prod_swag_network
    restart: always
    depends_on:
      - swag

networks:
  prod_swag_network:
    name: prod_swag_network
    external: true

volumes:
  static_value_prod:
    name: static_value_prod
  swag_volume_prod:
    name: swag_volume_prod
