version: '3.8'

services:
  frontend_develop:
    image: "${IMAGE_FRONT}:${IMAGE_FRONT_TAG}"
    container_name: frontend_prod
    environment:
      BASE_URL: ${FRONT_BASE_URL}
      API_BASE_URL: ${DEVELOP_API_BASE_URL}
    networks:
      - prod_swag_network
    ports:
      - "3005:3000"
    restart: always

networks:
  prod_swag_network:
    name: prod_swag_network
    external: true
