# Generated by Django 3.2.21 on 2023-11-06 00:31

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


CREATE_USER = """DO
$$
BEGIN
  IF NOT EXISTS (SELECT * FROM pg_user WHERE usename = 'postfix') THEN
     CREATE USER postfix WITH PASSWORD '{db_password}';
  END IF;
END
$$
;
GRANT CONNECT ON DATABASE {db_name} TO postfix;
GRANT USAGE ON SCHEMA public TO postfix;
GRANT SELECT ON postfix_virtual TO postfix;
GRANT SELECT ON postfix_recipient TO postfix;
"""
REMOVE_USER = """REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM postfix;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM postfix;
REVOKE ALL PRIVILEGES ON DATABASE {db_name} FROM postfix;
DROP USER postfix;
"""


def create_user(apps, schema_editor):
    if not schema_editor.connection.vendor.startswith('postgres'):
        return
    schema_editor.execute(CREATE_USER.format(db_name=settings.DATABASES["default"]["NAME"], db_password=settings.POSTFIX_DB_PASSWORD))


def remove_user(apps, schema_editor):
    if not schema_editor.connection.vendor.startswith('postgres'):
        return
    schema_editor.execute(REMOVE_USER.format(db_name=settings.DATABASES["default"]["NAME"]))


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Virtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='включено')),
                ('email', models.EmailField(max_length=254, verbose_name='виртуальный адрес', unique=True)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_email', to='library.author', verbose_name='автор')),
            ],
            options={
                'verbose_name': 'виртуальный адрес',
                'verbose_name_plural': 'виртуальные адреса',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='получатель')),
                ('virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='postfix.virtual')),
            ],
            options={
                'verbose_name': 'адрес назначения',
                'verbose_name_plural': 'адреса назначения',
            },
        ),
        migrations.RunPython(create_user, remove_user),
    ]
