# Generated by Django 3.2.21 on 2023-11-06 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Virtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True, verbose_name='включено')),
                ('email', models.EmailField(max_length=254, verbose_name='виртуальный адрес')),
            ],
            options={
                'verbose_name': 'виртуальный адрес',
                'verbose_name_plural': 'виртуальные адреса',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='получатель')),
                ('virtual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='postfix.virtual')),
            ],
            options={
                'verbose_name': 'адрес назначения',
                'verbose_name_plural': 'адреса назначения',
            },
        ),
    ]
