# Generated by Django 3.2.8 on 2021-10-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('content_pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
            ],
            options={
                'verbose_name': 'Блок сложной верстки для проекта',
                'verbose_name_plural': 'Блоки сложной верстки проектов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content_pages.content',),
        ),
        migrations.AddField(
            model_name='project',
            name='contents',
            field=models.ManyToManyField(through='articles.OrderedProjectContent', to='articles.ProjectContent', verbose_name='Контент сложной верстки'),
        ),
        migrations.AddField(
            model_name='orderedprojectcontent',
            name='content_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contents', to='articles.projectcontent', verbose_name='Модуль страницы'),
        ),
        migrations.AddField(
            model_name='orderedprojectcontent',
            name='project_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contents', to='articles.project'),
        ),
    ]
