# Generated by Django 3.2.11 on 2022-01-30 23:41

import apps.content_pages.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='image',
            field=models.ImageField(upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Заглавная картинка'),
        ),
    ]
