# Generated by Django 3.2.7 on 2021-09-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleBlog',
            new_name='BlogItem',
        ),
    ]
