# Generated by Django 3.2.8 on 2021-10-11 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_alter_content_options'),
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedprojectcontent',
            name='content_item',
        ),
        migrations.RemoveField(
            model_name='orderedprojectcontent',
            name='project_item',
        ),
        migrations.DeleteModel(
            name='ProjectContent',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contents',
        ),
        migrations.AddField(
            model_name='project',
            name='content_page',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='content_pages.contentpage', verbose_name='Блок элементов сложной верстки проекта'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderedProjectContent',
        ),
    ]
