# Generated by Django 3.2.8 on 2021-10-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('articles', '0002_rename_articleblog_blogitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='some description', max_length=500, verbose_name='Описание страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='some image', upload_to='images/projects/', verbose_name='Заглавная картинка проекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='some title', max_length=200, verbose_name='Заголовок страницы'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='articles.project', verbose_name='Блок элементов сложной верстки')),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label': 'content_pages', 'model__in': ['video', 'videosblock', 'imagesblock', 'performancesblock', 'playsblock', 'personsblock', 'link']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Блок сложной верстки проекта',
                'verbose_name_plural': 'Блоки сложной верстки проектов',
                'ordering': ['order'],
            },
        ),
    ]
