# Generated by Django 3.2.8 on 2021-10-12 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_pages', '0002_alter_content_options'),
        ('articles', '0003_auto_20211011_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContentPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content_pages.contentpage',),
        ),
        migrations.AlterField(
            model_name='project',
            name='content_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='content_pages.contentpage', verbose_name='Блок элементов сложной верстки проекта'),
        ),
    ]
