# Generated by Django 3.2.12 on 2022-02-21 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20220220_2205'),
        ('articles', '0003_data_delete_image_project_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogitem',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='blogitem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Статус'),
        ),
    ]
