# Generated by Django 3.2.12 on 2022-02-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_data_delete_image_project_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogitem',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='is_draft',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='blogitem',
            name='status',
            field=models.CharField(choices=[('in_progres', 'в работе'), ('review', 'на проверке'), ('ready_for_publish', 'готово к публикации'), ('published', 'опубликовано'), ('removed_from_publish', 'снято с публикации')], default='in_progres', max_length=25, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='status',
            field=models.CharField(choices=[('in_progres', 'в работе'), ('review', 'на проверке'), ('ready_for_publish', 'готово к публикации'), ('published', 'опубликовано'), ('removed_from_publish', 'снято с публикации')], default='in_progres', max_length=25, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('in_progres', 'в работе'), ('review', 'на проверке'), ('ready_for_publish', 'готово к публикации'), ('published', 'опубликовано'), ('removed_from_publish', 'снято с публикации')], default='in_progres', max_length=25, verbose_name='Статус'),
        ),
    ]
