# Generated by Django 3.2.7 on 2021-09-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_blocktext_blocktitle_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blocktext',
            old_name='images',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='blocktitle',
            old_name='name',
            new_name='title',
        ),
    ]
