# Generated by Django 3.2.8 on 2021-11-03 00:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('articles', '0003_auto_20211019_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogitem',
            options={'verbose_name': 'Запись блога', 'verbose_name_plural': 'Блог'},
        ),
        migrations.AlterModelOptions(
            name='projectcontent',
            options={'ordering': ('order',), 'verbose_name': 'Блок/элемент конструктора проекта', 'verbose_name_plural': 'Блоки/элементы конструктора проектов'},
        ),
        migrations.RemoveField(
            model_name='blogitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='name',
        ),
        migrations.AddField(
            model_name='blogitem',
            name='author_url',
            field=models.URLField(default=1, verbose_name='Ссылка на автора записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogitem',
            name='author_url_title',
            field=models.CharField(default=1, max_length=50, verbose_name='Подпись/название ссылки на автора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogitem',
            name='description',
            field=models.TextField(default=1, max_length=500, verbose_name='Описание страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog/', verbose_name='Заглавная картинка записи'),
        ),
        migrations.AddField(
            model_name='blogitem',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Заголовок страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsitem',
            name='description',
            field=models.TextField(default=1, max_length=500, verbose_name='Описание страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(null=True, upload_to='images/news/', verbose_name='Заглавная картинка новосте'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата публикации новости'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title',
            field=models.CharField(default=1, max_length=200, verbose_name='Заголовок страницы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='content_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='articles.project', verbose_name='Проект с конструктором'),
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'content_pages'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.CreateModel(
            name='NewsItemContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('content_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='articles.newsitem', verbose_name='Запись блога с конструктором')),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label': 'content_pages'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Блок/элемент конструктора новости',
                'verbose_name_plural': 'Блоки/элементы конструктора новостей',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='BlogItemContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('content_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='articles.blogitem', verbose_name='Запись блога с конструктором')),
                ('content_type', models.ForeignKey(limit_choices_to={'app_label': 'content_pages'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Блок/элемент конструктора записи блога',
                'verbose_name_plural': 'Блоки/элементы конструктора записей блога',
                'ordering': ('order',),
            },
        ),
    ]
