# Generated by Django 3.2.9 on 2021-11-21 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_description'),
        ('articles', '0004_auto_20211103_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='blogs',
            field=models.ManyToManyField(blank=True, related_name='linked_blogs', to='articles.BlogItem', verbose_name='Другие записи блогов'),
        ),
        migrations.AddField(
            model_name='blogitem',
            name='preamble',
            field=models.TextField(blank=True, max_length=500, verbose_name='Преамбула'),
        ),
        migrations.CreateModel(
            name='BlogPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('TEXT', 'Текст'), ('PHOTO', 'Фото'), ('ILLUSTRATION', 'Иллюстрации')], max_length=50, verbose_name='Роль в соавторстве')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_persons', to='articles.blogitem', verbose_name='Блог')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='blog_persons', to='core.person', verbose_name='Соавтор блога')),
            ],
            options={
                'verbose_name': 'Соавтор блога',
                'verbose_name_plural': 'Соавторы блогов',
                'ordering': ('role',),
            },
        ),
        migrations.AddField(
            model_name='blogitem',
            name='persons',
            field=models.ManyToManyField(related_name='blogs', through='articles.BlogPerson', to='core.Person', verbose_name='Соавторы'),
        ),
    ]
