# Generated by Django 3.2.8 on 2021-10-12 19:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('articles', '0004_auto_20211012_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Блок сложной верстки проекта',
                'verbose_name_plural': 'Блоки сложной верстки проектов',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ProjectContentPage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='content_page',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Заголовок страницы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Описание страницы'),
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='content_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='articles.project', verbose_name='Блок элементов сложной верстки'),
        ),
        migrations.AddField(
            model_name='projectcontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'content_pages'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
