# Generated by Django 3.2.12 on 2022-02-21 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220220_2205'),
        ('articles', '0004_auto_20220217_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.status', verbose_name='Статус'),
        ),
    ]
