# Generated by Django 3.2.12 on 2022-02-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20220223_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
