# Generated by Django 3.2.9 on 2021-11-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20211103_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(null=True, upload_to='images/news/', verbose_name='Заглавная картинка новостей'),
        ),
    ]
