# Generated by Django 3.2.7 on 2021-09-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210929_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='course',
            new_name='project',
        ),
    ]
