# Generated by Django 3.2.13 on 2022-04-27 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('articles', '0005_auto_20220228_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitemcontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'content_pages', 'model__in': ('contentunitrichtext', 'eventsblock', 'imagesblock', 'link', 'personsblock', 'playsblock', 'preamble', 'quote', 'text', 'title', 'videosblock')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='newsitemcontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'content_pages', 'model__in': ('contentunitrichtext', 'eventsblock', 'imagesblock', 'link', 'personsblock', 'playsblock', 'preamble', 'quote', 'text', 'title', 'videosblock')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='projectcontent',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'app_label': 'content_pages', 'model__in': ('contentunitrichtext', 'eventsblock', 'imagesblock', 'link', 'personsblock', 'playsblock', 'preamble', 'quote', 'text', 'title', 'videosblock')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
    ]
