# Generated by Django 3.2.12 on 2022-02-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220227_2236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogitem',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Запись блога', 'verbose_name_plural': 'Блог'},
        ),
    ]
