# Generated by Django 3.2.9 on 2021-12-02 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20211128_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
