# Generated by Django 3.2.7 on 2021-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_course_module_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='content_modules',
            field=models.ManyToManyField(related_name='projects', to='articles.Module', verbose_name='Модули контента'),
        ),
    ]
