# Generated by Django 3.2.9 on 2021-12-09 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_data_add_type_roles'),
        ('articles', '0007_alter_blogperson_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogperson',
            name='role',
            field=models.ForeignKey(limit_choices_to={'types__role_type': 'blog_persons_role'}, on_delete=django.db.models.deletion.RESTRICT, related_name='blog_persons', to='core.role', verbose_name='Роль в соавторстве'),
        ),
    ]
