# Generated by Django 3.2.9 on 2021-12-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_blogperson_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='intro',
            field=models.TextField(default='Межсезонные читки и обсуждение пьес из списка отмеченных отборщиками Любимовки.', help_text='Короткое интро к проекту. Показывается в списке проектов с заголовком.', max_length=200, verbose_name='Интро к проекту'),
            preserve_default=False,
        ),
    ]
