# Generated by Django 3.2.13 on 2022-07-25 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_again_overwrite_creators_articles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title',), 'permissions': (('access_level_1', 'Права журналиста'), ('access_level_2', 'Права редактора'), ('access_level_3', 'Права главреда')), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
