# Generated by Django 3.2.23 on 2024-03-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20221111_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_caption',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Заголовок описания'),
        ),
    ]
