# Generated by Django 3.2.11 on 2022-01-29 10:21

import ckeditor.fields
import django.core.validators
import random
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


def distribute_volunteers_to_festivals(apps, schema_editor):
    Volunteer = apps.get_model("info", "Volunteer")
    Festival = apps.get_model("info", "Festival")

    festivals = list(Festival.objects.all())

    for obj in Volunteer.objects.all():
        obj.festival = random.choice(festivals)
        obj.save()


class Migration(migrations.Migration):

    replaces = [('info', '0003_auto_20211005_2119'), ('info', '0004_auto_20211017_1522'), ('info', '0005_auto_20211110_0116'), ('info', '0006_auto_20211115_2025'), ('info', '0007_partner_in_footer_partner'), ('info', '0008_alter_partner_options'), ('info', '0009_auto_20211210_1839'), ('info', '0010_alter_partner_in_footer_partner'), ('info', '0011_auto_20220113_0014'), ('info', '0012_festival_start_date_before_end_date'), ('info', '0013_review_text_limit'), ('info', '0014_alter_volunteer_review_text'), ('info', '0015_alter_festivalteam_person'), ('info', '0016_auto_20220121_1138'), ('info', '0017_alter_place_description')]

    dependencies = [
        ('info', '0001_initial'),
        ('core', '0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='picture',
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(help_text='Загрузите логотип партнёра', upload_to='images/info/partnerslogo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('general', 'Генеральный партнер'), ('festival', 'Партнер фестиваля'), ('info', 'Информационный партнер')], max_length=8, verbose_name='Тип'),
        ),
        migrations.RenameField(
            model_name='question',
            old_name='email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='author_name',
        ),
        migrations.AlterField(
            model_name='festival',
            name='cities_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество участвующих городов'),
        ),
        migrations.AlterField(
            model_name='festivalteam',
            name='team',
            field=models.CharField(choices=[('art', 'Арт-дирекция фестиваля'), ('fest', 'Команда фестиваля')], max_length=5, verbose_name='Тип команды'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(2, 'Вопрос должен состоять более чем из 2 символов')], verbose_name='Текст вопроса'),
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='review',
            new_name='review_text',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='review_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок отзыва'),
        ),
        migrations.RemoveField(
            model_name='festival',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='teams',
        ),
        migrations.AddField(
            model_name='partner',
            name='in_footer_partner',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, чтобы показать логотип партнёра внизу страницы', verbose_name='Отображение внизу страницы'),
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('type',), 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AddField(
            model_name='festival',
            name='press_release_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение для страницы пресс-релизов'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('festival', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='press_releases', to='info.festival', verbose_name='Фестиваль')),
            ],
            options={
                'verbose_name': 'Пресс-релиз',
                'verbose_name_plural': 'Пресс-релизы',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='in_footer_partner',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, чтобы показать логотип партнёра внизу страницы', verbose_name='Отображать внизу страницы'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022, unique=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год фестиваля'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год участия в фестивале'),
        ),
        migrations.AddConstraint(
            model_name='festival',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', django.db.models.expressions.F('end_date'))), name='start_date_before_end_date'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='review_text',
            field=models.TextField(max_length=500, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='review_text',
            field=models.TextField(blank=True, max_length=500, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='festivalteam',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Человек'),
        ),
        migrations.RemoveConstraint(
            model_name='volunteer',
            name='unique_volunteer',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='volunteers',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='year',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='info.festival', verbose_name='Фестиваль'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='volunteer',
            constraint=models.UniqueConstraint(fields=('person', 'festival'), name='unique_volunteer'),
        ),
        migrations.RunPython(
            distribute_volunteers_to_festivals,
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
    ]
