# Generated by Django 3.2.11 on 2022-02-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='press_release_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Изображение для страницы пресс-релизов'),
        ),
    ]
