# Generated by Django 3.2.11 on 2022-02-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_volunteer_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='press_release_image',
            field=models.ImageField(blank=True, upload_to='images/info/press_releases', verbose_name='Изображение для страницы пресс-релизов'),
        ),
    ]
