# Generated by Django 3.2.7 on 2021-10-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_festival_programms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='picture',
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(help_text='Загрузите логотип партнёра', upload_to='images/info/partnerslogo', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('general', 'Генеральный партнер'), ('festival', 'Партнер фестиваля'), ('info', 'Информационный партнер')], max_length=8, verbose_name='Тип'),
        ),
    ]
