# Generated by Django 3.2.7 on 2021-09-26 23:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('info', '0003_auto_20210922_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год участия в фестивале')),
            ],
            options={
                'verbose_name': 'Волонтёр фестиваля',
                'verbose_name_plural': 'Волонтёры фестиваля',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('city', models.CharField(max_length=50, verbose_name='Город проживания')),
                ('email', models.EmailField(max_length=200, verbose_name='Электронная почта')),
                ('image', models.ImageField(upload_to='images/person_avatars', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ('last_name',),
            },
        ),
        migrations.AlterField(
            model_name='partner',
            name='picture',
            field=models.ImageField(upload_to='images/info/partnerslogo', verbose_name='Логотип'),
        ),
        migrations.CreateModel(
            name='VolunteerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('review', models.TextField(verbose_name='Текст отзыва')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.festivalvolunteer', verbose_name='Волонтёр')),
            ],
            options={
                'verbose_name': 'Отзыв волонтёра',
                'verbose_name_plural': 'Отзывы волнтёров',
            },
        ),
        migrations.CreateModel(
            name='Trustee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('appointment', models.CharField(max_length=150, verbose_name='Должность')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Попечитель фестиваля',
                'verbose_name_plural': 'Попечители фестиваля',
            },
        ),
        migrations.AddField(
            model_name='festivalvolunteer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.person', verbose_name='Человек'),
        ),
        migrations.CreateModel(
            name='FestivalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('team', models.SmallIntegerField(choices=[(1, 'Арт-дирекция фестиваля'), (2, 'Команда фестиваля')], verbose_name='Тип команды')),
                ('appointment', models.CharField(max_length=150, verbose_name='Должность')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Команда фестиваля',
                'verbose_name_plural': 'Команды фестиваля',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='Дата начала фестиваля')),
                ('end_date', models.DateField(verbose_name='Дата окончания фестиваля')),
                ('description', models.CharField(max_length=200, verbose_name='Описание фестиваля')),
                ('year', models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год фестиваля')),
                ('programms', models.CharField(max_length=10, verbose_name='Программы фестиваля')),
                ('plays_count', models.PositiveIntegerField(default=1, verbose_name='Общее количество пьес')),
                ('selected_plays_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество отобранных пьес')),
                ('selectors_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество отборщиков пьес')),
                ('volunteers_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество волонтёров фестиваля')),
                ('events_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество событий фестиваля')),
                ('cities_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество учавствующих городов')),
                ('video_linl', models.URLField(max_length=250, verbose_name='Ссылка на видео о фестивале')),
                ('blog_entries', models.CharField(max_length=10, verbose_name='Записи в блоге о фестивале')),
                ('images', models.ManyToManyField(related_name='festivalimages', to='core.Image', verbose_name='Изображения')),
                ('reviews', models.ManyToManyField(related_name='volunteerreviews', to='info.VolunteerReview', verbose_name='Отзывы волонтёров о фестивале')),
                ('team', models.ManyToManyField(related_name='festivalteams', to='info.FestivalTeam', verbose_name='Арт-дирекция и команда')),
                ('trustees', models.ManyToManyField(related_name='festivaltrustees', to='info.Trustee', verbose_name='Попечители фестиваля')),
                ('volunteers', models.ManyToManyField(related_name='festivalvolunteers', to='info.FestivalVolunteer', verbose_name='Волонтёры фестиваля')),
            ],
            options={
                'verbose_name': 'Фестиваль',
                'verbose_name_plural': 'Фестивали',
                'ordering': ['-year'],
            },
        ),
    ]
