# Generated by Django 3.2.12 on 2022-02-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_festival_press_release_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ('person__last_name',), 'verbose_name': 'Волонтёр фестиваля', 'verbose_name_plural': 'Волонтёры фестиваля'},
        ),
        migrations.RenameModel("FestivalTeam", "FestivalTeamMember")
    ]
