# Generated by Django 3.2.7 on 2021-10-17 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20211005_2119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='name',
            new_name='author_name',
        ),
        migrations.AlterField(
            model_name='festival',
            name='cities_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество участвующих городов'),
        ),
        migrations.AlterField(
            model_name='festivalteam',
            name='team',
            field=models.CharField(choices=[('art', 'Арт-дирекция фестиваля'), ('fest', 'Команда фестиваля')], max_length=5, verbose_name='Тип команды'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(2, 'Вопрос должен состоять более чем из 2 символов')], verbose_name='Текст вопроса'),
        ),
    ]
