# Generated by Django 3.2.7 on 2021-10-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20211005_2119'),
        ('info', '0003_auto_20211013_0900'),
    ]

    operations = [
    ]
