# Generated by Django 3.2.7 on 2021-09-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20210922_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос или предложение', 'verbose_name_plural': 'Вопросы или предложения'},
        ),
        migrations.AddField(
            model_name='question',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
