# Generated by Django 3.2.7 on 2021-10-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_merge_0003_auto_20211005_2119_0003_auto_20211013_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalteam',
            name='team',
            field=models.SmallIntegerField(choices=[('art', 'Арт-дирекция фестиваля'), ('fest', 'Команда фестиваля')], verbose_name='Тип команды'),
        ),
    ]
