# Generated by Django 3.2.7 on 2021-09-27 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210926_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trustee',
            new_name='Sponsor',
        ),
        migrations.RenameField(
            model_name='festival',
            old_name='team',
            new_name='teams',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='trustees',
        ),
        migrations.AddField(
            model_name='festival',
            name='sponsors',
            field=models.ManyToManyField(related_name='festivalsponsors', to='info.Sponsor', verbose_name='Попечители фестиваля'),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Электронная почта'),
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год участия в фестивале')),
                ('review', models.TextField(verbose_name='Текст отзыва')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Волонтёр фестиваля',
                'verbose_name_plural': 'Волонтёры фестиваля',
            },
        ),
        migrations.AlterField(
            model_name='festival',
            name='volunteers',
            field=models.ManyToManyField(related_name='volunteers', to='info.Volunteer', verbose_name='Волонтёры фестиваля'),
        ),
        migrations.AlterField(
            model_name='volunteerreview',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.volunteer', verbose_name='Волонтёр'),
        ),
        migrations.DeleteModel(
            name='FestivalVolunteer',
        ),
    ]
