# Generated by Django 3.2.9 on 2021-11-15 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20211110_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='teams',
        ),
    ]
