# Generated by Django 3.2.7 on 2021-09-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20210924_1051'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_place'),
        ),
    ]
