# Generated by Django 3.2.7 on 2021-09-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20210926_2316'),
        ('info', '0005_auto_20210924_1051'),
    ]

    operations = [
    ]
