# Generated by Django 3.2.7 on 2021-09-28 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210928_1915'),
        ('info', '0005_auto_20210927_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerreview',
            name='volunteer',
        ),
        migrations.RenameField(
            model_name='festival',
            old_name='video_linl',
            new_name='video_link',
        ),
        migrations.RenameField(
            model_name='festivalteam',
            old_name='appointment',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='appointment',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='reviews',
        ),
        migrations.AddField(
            model_name='festival',
            name='reviews',
            field=models.CharField(default=0, max_length=3, verbose_name='Отзывы волонтёров о фестивале'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='festival',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021, unique=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год фестиваля'),
        ),
        migrations.AlterField(
            model_name='festivalteam',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Человек'),
        ),
        migrations.AddConstraint(
            model_name='festivalteam',
            constraint=models.UniqueConstraint(fields=('person', 'team'), name='unique_person_team'),
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.UniqueConstraint(fields=('person', 'position'), name='unique_sponsor'),
        ),
        migrations.AddConstraint(
            model_name='volunteer',
            constraint=models.UniqueConstraint(fields=('person', 'year'), name='unique_volunteer'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='VolunteerReview',
        ),
    ]
