# Generated by Django 3.2.7 on 2021-10-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_festivalteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalteam',
            name='team',
            field=models.CharField(choices=[('art', 'Арт-дирекция фестиваля'), ('fest', 'Команда фестиваля')], max_length=5, verbose_name='Тип команды'),
        ),
    ]
