# Generated by Django 3.2.12 on 2022-02-25 23:42

from django.db import migrations, models

import apps.content_pages.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('info', '005_festivalteam_is_pr_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(help_text='Загрузите логотип партнёра', upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Логотип'),
        ),
    ]
