# Generated by Django 3.2.9 on 2021-12-04 20:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20211115_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageYearPressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение для ')),
                ('festival', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_press', to='info.festival', verbose_name='Фестиваль')),
            ],
            options={
                'verbose_name': 'Изображение для страницы пресс-релиза',
                'verbose_name_plural': 'Изображения для страниц пресс-релизов',
                'ordering': ('festival__year',),
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('festival_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_releases', to='info.imageyearpressrelease', verbose_name='Связан с фестивалем')),
            ],
            options={
                'verbose_name': 'Пресс-релиз',
                'verbose_name_plural': 'Пресс-релизы',
                'ordering': ('-created',),
            },
        ),
    ]
