# Generated by Django 3.2.9 on 2021-12-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_partner_in_footer_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('type',), 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
    ]
