# Generated by Django 3.2.9 on 2021-12-04 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_pressrelease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressrelease',
            name='year',
        ),
        migrations.CreateModel(
            name='ImageYearPressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение для ')),
                ('festival', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='for_press', to='info.festival', verbose_name='Фестиваль')),
            ],
            options={
                'verbose_name': 'Изображение для фестиваля',
                'verbose_name_plural': 'Изображения для фестивалей',
                'ordering': ('festival__year',),
            },
        ),
        migrations.AddField(
            model_name='pressrelease',
            name='festival_through',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='press_releases', to='info.imageyearpressrelease', verbose_name='Связан с фестивалем'),
            preserve_default=False,
        ),
    ]
