# Generated by Django 3.2.9 on 2021-12-10 18:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_alter_partner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='press_release_image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Изображение для страницы пресс-релизов'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500, unique=True, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('festival', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='press_releases', to='info.festival', verbose_name='Фестиваль')),
            ],
            options={
                'verbose_name': 'Пресс-релиз',
                'verbose_name_plural': 'Пресс-релизы',
                'ordering': ('-created',),
            },
        ),
    ]
