# Generated by Django 3.2.10 on 2021-12-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_auto_20211210_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='in_footer_partner',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, чтобы показать логотип партнёра внизу страницы', verbose_name='Отображать внизу страницы'),
        ),
    ]
