# Generated by Django 3.2.10 on 2022-01-10 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_partner_in_footer_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022, unique=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год фестиваля'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='year',
            field=models.PositiveSmallIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год участия в фестивале'),
        ),
    ]
