# Generated by Django 3.2.12 on 2022-03-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_artteammember_festteammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name="FestivalTeamMember",
            name="is_pr_manager",
            field=models.BooleanField(
                default=False,
                verbose_name="PR-директор",
                help_text="Поставьте галочку, чтобы назначить человека PR-директором",
            )
        )
    ]
