# Generated by Django 3.2.10 on 2022-01-13 19:45

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20220113_0014'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='festival',
            constraint=models.CheckConstraint(check=models.Q(('start_date__lt', django.db.models.expressions.F('end_date'))), name='start_date_before_end_date'),
        ),
    ]
