# Generated by Django 3.2.12 on 2022-03-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_template_id'),
        ('info', '0012_auto_20220324_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('review_title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок отзыва')),
                ('review_text', models.TextField(blank=True, max_length=2000, verbose_name='Текст отзыва')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectors', to='info.festival', verbose_name='Фестиваль')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Отборщик фестиваля',
                'verbose_name_plural': 'Отборщики фестиваля',
                'ordering': ('person__last_name', 'person__first_name'),
            },
        ),
        migrations.AddConstraint(
            model_name='selector',
            constraint=models.UniqueConstraint(fields=('person', 'festival'), name='unique_selector'),
        ),
    ]
