# Generated by Django 3.2.11 on 2022-01-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_review_text_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='review_text',
            field=models.TextField(blank=True, max_length=500, verbose_name='Текст отзыва'),
        ),
    ]
