# Generated by Django 3.2.12 on 2022-03-31 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_auto_20220329_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='festivalteammember',
            old_name='is_pr_manager',
            new_name='is_pr_director',
        ),
    ]
