# Generated by Django 3.2.12 on 2022-04-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_rename_is_pr_manager_festivalteammember_is_pr_director'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
