# Generated by Django 3.2.11 on 2022-01-20 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_alter_volunteer_review_text'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='volunteer',
            name='unique_volunteer',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='volunteers',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='year',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='volunteer', to='info.festival', verbose_name='Фестиваль'),
            preserve_default=False,
        ),
    ]
