# Generated by Django 3.2.11 on 2022-01-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_alter_festivalteam_person'),
        ('info', '0015_auto_20220121_1138'),
    ]

    operations = [
    ]
