# Generated by Django 3.2.11 on 2022-01-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20220120_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volunteers', to='info.festival', verbose_name='Фестиваль'),
        ),
    ]
