# Generated by Django 3.2.12 on 2022-04-29 12:27

from django.db import migrations, models

def set_order_partner(apps, schema_editor):
    Partner = apps.get_model("info", "Partner")
    for partner in Partner.objects.all():
        partner.order = partner.id
        partner.save()

def set_order_sponsor(apps, schema_editor):
    Sponsor = apps.get_model("info", "Sponsor")
    for sponsor in Sponsor.objects.all():
        sponsor.order = sponsor.id
        sponsor.save()

def set_order_volunteer(apps, schema_editor):
    Volunteer = apps.get_model("info", "Volunteer")
    for volunteer in Volunteer.objects.all():
        volunteer.order = volunteer.id
        volunteer.save()

def set_order_festivalteammember(apps, schema_editor):
    FestivalTeamMember = apps.get_model("info", "FestivalTeamMember")
    for member in FestivalTeamMember.objects.all():
        member.order = member.id
        member.save()

def set_order_place(apps, schema_editor):
    Place = apps.get_model("info", "Place")
    for place in Place.objects.all():
        place.order = place.id
        place.save()

def set_order_selector(apps, schema_editor):
    Selector = apps.get_model("info", "Selector")
    for selector in Selector.objects.all():
        selector.order = selector.id
        selector.save()

def order_model(Model):
    for obj in Model.objects.all():
        obj.order = obj.id
        obj.save()

def set_order(apps, schema_editor):
    models = []
    models.append(apps.get_model("info", "Partner"))
    models.append(apps.get_model("info", "Sponsor"))
    models.append(apps.get_model("info", "Volunteer"))
    models.append(apps.get_model("info", "FestivalTeamMember"))
    models.append(apps.get_model("info", "Place"))
    models.append(apps.get_model("info", "Selector"))
    for model in models:
        order_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_delete_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('order',), 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('order',), 'verbose_name': 'Попечитель фестиваля', 'verbose_name_plural': 'Попечители фестиваля'},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ('order',), 'verbose_name': 'Волонтёр фестиваля', 'verbose_name_plural': 'Волонтёры фестиваля'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterModelOptions(
            name='festivalteammember',
            options={'ordering': ('order',), 'verbose_name': 'Команда фестиваля', 'verbose_name_plural': 'Команды фестиваля'},
        ),
        migrations.AddField(
            model_name='festivalteammember',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('order',), 'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterModelOptions(
            name='selector',
            options={'ordering': ('order',), 'verbose_name': 'Отборщик фестиваля', 'verbose_name_plural': 'Отборщики фестиваля'},
        ),
        migrations.AddField(
            model_name='selector',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Сортировка'),
        ),
        migrations.RunPython(
            set_order,
        ),
    ]
