# Generated by Django 3.2.12 on 2022-05-04 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('plays_links', 'Пьесы'), ('additional_links', 'Дополнительно')], max_length=25, verbose_name='Тип ссылки')),
                ('description', models.TextField(max_length=250, verbose_name='Описание ссылки')),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Ссылка с описанием',
                'verbose_name_plural': 'Ссылки с описанием',
            },
        ),
        migrations.CreateModel(
            name='FestivalInfoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер ссылки')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_links', to='info.festival', verbose_name='Фестиваль')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='festival_links', to='info.infolink', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Ссылка фестиваля',
                'verbose_name_plural': 'Ссылки фестиваля',
                'ordering': ('order',),
            },
        ),
        migrations.AddConstraint(
            model_name='festivalinfolink',
            constraint=models.UniqueConstraint(fields=('festival', 'link'), name='unique_festival_link'),
        ),
        migrations.AddField(
            model_name='festival',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='festival', through='info.FestivalInfoLink', to='info.InfoLink', verbose_name='Ссылки'),
        ),
    ]
