# Generated by Django 3.2.11 on 2022-01-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_alter_festivalteam_person'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='volunteer',
            name='unique_volunteer',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='volunteers',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='year',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='festival',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='info.festival', verbose_name='Фестиваль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AddConstraint(
            model_name='volunteer',
            constraint=models.UniqueConstraint(fields=('person', 'festival'), name='unique_volunteer'),
        ),
    ]
