# Generated by Django 3.2.12 on 2022-04-29 12:27

from django.db import migrations, models

def order_model(Model):
    for obj in Model.objects.all():
        obj.order = obj.id
        obj.save()

def set_order(apps, schema_editor):
    """Set order to already existing objects.

    Without this operation SortableAdminMixin will not work
    for existing objects. Also you can use this command:
    './manage.py reorder APP_NAME.MODEl_NAME.'
    """

    models = []
    models.append(apps.get_model("info", "Partner"))
    models.append(apps.get_model("info", "Sponsor"))
    models.append(apps.get_model("info", "Volunteer"))
    models.append(apps.get_model("info", "FestivalTeamMember"))
    models.append(apps.get_model("info", "Place"))
    models.append(apps.get_model("info", "Selector"))
    for model in models:
        order_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_infolink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('order',), 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('order',), 'verbose_name': 'Попечитель фестиваля', 'verbose_name_plural': 'Попечители фестиваля'},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ('order',), 'verbose_name': 'Волонтёр фестиваля', 'verbose_name_plural': 'Волонтёры фестиваля'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterModelOptions(
            name='festivalteammember',
            options={'ordering': ('order',), 'verbose_name': 'Команда фестиваля', 'verbose_name_plural': 'Команды фестиваля'},
        ),
        migrations.AddField(
            model_name='festivalteammember',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('order',), 'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.AlterModelOptions(
            name='selector',
            options={'ordering': ('order',), 'verbose_name': 'Отборщик фестиваля', 'verbose_name_plural': 'Отборщики фестиваля'},
        ),
        migrations.AddField(
            model_name='selector',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.RunPython(
            set_order,
        ),
    ]
