# Generated by Django 3.2.11 on 2022-01-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_20220121_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Описание'),
        ),
    ]
