# Generated by Django 3.2.12 on 2022-05-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_auto_20220429_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='selector',
            name='festival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Год в формате дата-время'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='festival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Год в формате дата-время'),
        ),
    ]
