# Generated by Django 3.2.11 on 2022-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_alter_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='festivalteam',
            name='is_pr_manager',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, чтобы назначить человека PR-менеджером', verbose_name='PR-менеджер'),
        ),
    ]
