# Generated by Django 3.2.11 on 2022-02-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_festival_press_release_image'),
        ('info', '0018_festivalteam_is_pr_manager'),
    ]

    operations = [
    ]
