# Generated by Django 3.2.11 on 2022-02-11 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_volunteer_review_text'),
        ('info', '0018_festivalteam_is_pr_manager'),
    ]

    operations = [
    ]
