# Generated by Django 3.2.13 on 2022-07-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0020_rename_press_release_image_festival_festival_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressrelease',
            name='title',
        ),
    ]
