# Generated by Django 3.2.13 on 2022-07-06 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0021_remove_pressrelease_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressrelease',
            name='festival',
            field=models.OneToOneField(limit_choices_to={'press_releases': None}, on_delete=django.db.models.deletion.CASCADE, related_name='press_releases', to='info.festival', verbose_name='Фестиваль'),
        ),
    ]
