# Generated by Django 3.2.13 on 2022-07-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_role_slug'),
        ('info', '0022_alter_pressrelease_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivalteammember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.person', verbose_name='Человек'),
        ),
    ]
