# Generated by Django 3.2.13 on 2022-07-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_alter_festivalteammember_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.CharField(blank=True, help_text='Поле не обязательное', max_length=200, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_general',
            field=models.BooleanField(default=False, help_text='Поставьте галочку, чтобы сделать партнёра генеральным', verbose_name='Генеральный партнер'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type',
            field=models.CharField(choices=[('festival', 'Партнер фестиваля'), ('info', 'Информационный партнер')], max_length=8, verbose_name='Тип'),
        ),
    ]
