# Generated by Django 3.2.14 on 2022-08-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0023_alter_festivalteammember_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='selectors_page_link',
            field=models.URLField(blank=True, verbose_name='Ссылка на новость об отборщиках'),
        ),
    ]
