# Generated by Django 3.2.13 on 2022-08-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0024_auto_20220730_0909'),
        ('info', '0024_festival_selectors_page_link'),
    ]

    operations = [
    ]
