# Generated by Django 3.2.13 on 2022-09-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='start_date',
            field=models.DateField(unique_for_year='start_date', verbose_name='Дата начала фестиваля'),
        ),
    ]
