# Generated by Django 3.2.13 on 2022-09-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0026_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='festival',
            options={'ordering': ['-start_date'], 'verbose_name': 'Фестиваль', 'verbose_name_plural': 'Фестивали'},
        ),
        migrations.RemoveField(
            model_name='festival',
            name='year',
        ),
    ]
