# Generated by Django 3.2.13 on 2022-09-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0027_alter_festival_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала фестиваля'),
        ),
    ]
