# Generated by Django 3.2.16 on 2023-01-11 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0028_alter_festival_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='year',
            field=models.PositiveSmallIntegerField(default=2023, unique=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год фестиваля'),
        ),
    ]
