# Generated by Django 3.2.20 on 2024-01-09 09:33

import apps.info.models.festival
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0029_alter_festival_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='year',
            field=models.PositiveSmallIntegerField(default=apps.info.models.festival.Festival.current_year, unique=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2500)], verbose_name='Год фестиваля'),
        ),
    ]
