# Generated by Django 3.2.7 on 2021-09-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='HistoryQuestion',
        ),
    ]
