# Generated by Django 3.2.8 on 2021-10-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('what-we-do', 'Страница "Что мы делаем"'), ('ideology', 'Страница "Идеология"'), ('history', 'Страница "История"')], max_length=10, verbose_name='Название страницы')),
                ('data', models.TextField(verbose_name='Данные, отображаемые на странице')),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
            },
        ),
    ]
