# Generated by Django 3.2.11 on 2022-02-10 16:07

from django.db import migrations

def add_playsupply_settings(apps, schema_editor):

    Setting = apps.get_model("core", "Setting")

    Setting.objects.get_or_create(
        field_type="TEXT",
        group="PLAY_SUPPLY",
        settings_key="SPREADSHEET_ID",
        text="1PB-Rzd46wHpldZptqc7CEn9VNkv3iRJuo9e87Xtpgb4",
        description="id Google таблицы",
    )
    Setting.objects.get_or_create(
        field_type="TEXT",
        group="PLAY_SUPPLY",
        settings_key="SHEET",
        text="Лист1",
        description="Наименование листа Google таблицы",
    )
    form_to_submit_a_play = Setting.objects.get(
        settings_key="form_to_submit_a_play",
    )
    form_to_submit_a_play.group = "PLAY_SUPPLY"
    form_to_submit_a_play.description="Открыт приём пьес"
    form_to_submit_a_play.settings_key="plays_reception_is_open"
    form_to_submit_a_play.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_setting_group'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingPlaySupply',
            fields=[
            ],
            options={
                'verbose_name': 'Настройки подачи пьес',
                'verbose_name_plural': 'Настройки подачи пьес',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.setting',),
        ),
        migrations.RunPython(
            add_playsupply_settings,
        )
    ]
