# Generated by Django 3.2.7 on 2021-10-18 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_person_image'),
        ('main', '0002_delete_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300, verbose_name='Текст')),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Festival_settings', 'Настройки страницы фестиваля'), ('Main_page_settings', 'Настройки главной страницы'), ('History_page_settings', 'Настройки страницы История'), ('About_festival_what_we_do_page_settings', 'Настройки страницы О фестивале. Что мы делаем?'), ('About_festival_ideology_page_settings', 'Настройки страницы О фестивале. Идеология?'), ('Other', 'Прочие')], max_length=40, verbose_name='Выбор типа настроек')),
                ('value_type', models.CharField(choices=[('Email_value', 'Email'), ('Settings_with_blocks', 'Информационные блоки'), ('Bool_value', 'Настройки Да/Нет'), ('Text_value', 'Текст'), ('Image', 'Картинка'), ('Title_description_images_and_texts_value', 'Настройка страницы')], max_length=40, verbose_name='Выбор типа значения настроек')),
                ('name', models.CharField(max_length=100, verbose_name='Название (значение key)')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('text', models.CharField(blank=True, max_length=40, verbose_name='Текстовое значение')),
                ('image', models.ImageField(upload_to='main/', verbose_name='Картинка')),
                ('boolean', models.BooleanField(default=False, verbose_name='Да или Нет')),
                ('images_for_page', models.ManyToManyField(blank=True, related_name='pages', to='core.Image', verbose_name='Картинки для страницы')),
                ('texts_for_page', models.ManyToManyField(blank=True, related_name='pages_text', to='main.Text', verbose_name='Текст для страницы')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Описание или заголовок')),
                ('value', models.CharField(max_length=300, verbose_name='Текст')),
                ('block_text', models.TextField(max_length=300, verbose_name='Текст')),
                ('block_image', models.ImageField(upload_to='main/', verbose_name='Картинка')),
                ('block_item', models.CharField(choices=[('First', 'Первый'), ('Second', 'Второй'), ('Main', 'Главный')], max_length=30, verbose_name='Выбор номер блока')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.mainsettings')),
            ],
            options={
                'verbose_name': 'Информационный блок',
                'verbose_name_plural': 'Информационные блоки',
            },
        ),
    ]
