# Generated by Django 3.2.7 on 2021-10-21 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_person_image'),
        ('main', '0002_delete_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Festival_settings', 'Настройки фестиваля'), ('Main_page_settings', 'Настройки главной страницы'), ('History_page_settings', 'Настройки страницы истории'), ('About_festival_what_we_do_page_settings', 'Настройки страницы О фестивале. Что мы делаем?'), ('About_festival_ideology_page_settings', 'Настройки страницы О фестивале. Идеология.'), ('Other_settings', 'Прочие настройки')], max_length=40, verbose_name='Выбор типа настроек')),
                ('settings_key', models.CharField(choices=[('Festival_status', 'Состояние фестиваля (Да/Нет)'), ('Main_title', 'Заголовок для главной страницы'), ('Main_description', 'Описание не главной страницы'), ('Main_url', 'Ссылка для главной страницы'), ('Main_image', 'Картинка для главной страницы'), ('What_we_do_main_title', 'Главный заголовок страницы Что мы делаем?'), ('What_we_do_title', 'Подзаголовок страницы Что мы делаем?'), ('What_we_do_page_info', 'Информационные блоки для страницы Что мы делаем?'), ('Ideology_first_title', 'Первый подзаголовок страницы Идеология'), ('Ideology_second_title', 'Второй подзаголовок страницы Идеология'), ('Ideology_info', 'Информационные блоки для страницы Идеология'), ('History_title', 'Подзаголовок страницы История'), ('History_info', 'Информационные блоки для страницы История'), ('Mail_send_to', 'Email для отправки вопросов на сайте')], max_length=40, unique=True, verbose_name='Выбор ключа настроек')),
                ('boolean', models.BooleanField(default=False, verbose_name='Да или Нет')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=100, verbose_name='Текст')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, upload_to='main/', verbose_name='Изображение')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Общие настройки',
                'verbose_name_plural': 'Общие настройки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SettingsImageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_order', models.PositiveIntegerField(verbose_name='Порядковый номер картинки на странице сверху вниз')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_blocks', to='core.image', verbose_name='Картинка')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='main.mainsettings', verbose_name='Настройка')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
                'ordering': ['image_order'],
            },
        ),
        migrations.AddField(
            model_name='mainsettings',
            name='images_for_page',
            field=models.ManyToManyField(blank=True, related_name='images', through='main.SettingsImageRelation', to='core.Image', verbose_name='Картинки для страницы'),
        ),
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(blank=True, max_length=100, verbose_name='Описание или заголовок блока')),
                ('block_text', models.TextField(max_length=300, verbose_name='Текст блока')),
                ('block', models.CharField(choices=[('Main', 'Главный блок'), ('First', 'Первая группа блоков, относящаяся к первому подзаголовку'), ('Second', 'Вторая группа блоков, относящаяся к первому подзаголовку')], max_length=30, verbose_name='Принадлежность к блоку')),
                ('block_order', models.PositiveIntegerField(verbose_name='Порядок отображения внутри блоков странице сверху вниз')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainsettings')),
            ],
            options={
                'verbose_name': 'Информационный блок',
                'verbose_name_plural': 'Информационные блоки',
                'ordering': ['block_order'],
            },
        ),
        migrations.AddConstraint(
            model_name='settingsimagerelation',
            constraint=models.UniqueConstraint(fields=('settings', 'image_order'), name='unique_image_order'),
        ),
        migrations.AddConstraint(
            model_name='infoblock',
            constraint=models.UniqueConstraint(fields=('block', 'block_order'), name='unique_order'),
        ),
    ]
