# Generated by Django 3.2.12 on 2022-02-25 23:42

import apps.content_pages.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_settingplaysupply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to=apps.content_pages.utilities.path_by_app_label_and_class_name, verbose_name='Картинка'),
        ),
    ]
