# Generated by Django 3.2.9 on 2021-11-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_delete_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='images/main/banner', verbose_name='Картинка')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
