# Generated by Django 3.2.9 on 2021-11-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Банер для главной странице', 'verbose_name_plural': 'Банеры для главной странице'},
        ),
    ]
