# Generated by Django 3.2.7 on 2021-10-22 19:50

from django.db import migrations
from django.core.management import call_command


def loadfixture(apps, schema_editor):
    call_command('loaddata', 'settings.json')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
    ]
