# Generated by Django 3.2.7 on 2021-10-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainSettings',
        ),
    ]
