# Generated by Django 3.2.12 on 2022-05-11 08:50

from django.db import migrations, models


def order_model(Model):
    for obj in Model.objects.all():
        obj.order = obj.id
        obj.save()

def set_order(apps, schema_editor):
    """Set order to already existing objects.

    Without this operation SortableAdminMixin will not work
    for existing objects. Also you can use this command:
    './manage.py reorder APP_NAME.MODEl_NAME.'
    """

    models = []
    models.append(apps.get_model("main", "Banner"))
    for model in models:
        order_model(model)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('order',), 'verbose_name': 'Банер для главной странице', 'verbose_name_plural': 'Банеры для главной странице'},
        ),
        migrations.AddField(
            model_name='banner',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.RunPython(
            set_order,
        )
    ]
