# Generated by Django 3.2.7 on 2021-10-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoblock',
            options={'ordering': ['block_order'], 'verbose_name': 'Информационный блок', 'verbose_name_plural': 'Информационные блоки'},
        ),
        migrations.RemoveField(
            model_name='infoblock',
            name='block_item',
        ),
        migrations.AddField(
            model_name='infoblock',
            name='block',
            field=models.CharField(choices=[('Main', 'Главный блок'), ('First', 'Первая группа блоков, относящаяся к первому подзаголовку'), ('Second', 'Вторая группа блоков, относящаяся к первому подзаголовку')], default=1, max_length=30, verbose_name='Принадлежность к блоку'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infoblock',
            name='block_order',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='Порядок отображения внутри блоков странице сверху вниз'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infoblock',
            name='block_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание или заголовок блока'),
        ),
        migrations.AlterField(
            model_name='infoblock',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mainsettings'),
        ),
        migrations.AlterField(
            model_name='mainsettings',
            name='settings_key',
            field=models.CharField(choices=[('Festival_status', 'Состояние фестиваля (Да/Нет)'), ('Main_title', 'Заголовок для главной страницы'), ('Main_description', 'Описание не главной страницы'), ('Main_url', 'Ссылка для главной страницы'), ('Main_image', 'Картинка для главной страницы'), ('What_we_do_main_title', 'Главный заголовок страницы Что мы делаем?'), ('What_we_do_title', 'Подзаголовок страницы Что мы делаем?'), ('What_we_do_page_info', 'Информационные блоки для страницы Что мы делаем?'), ('Ideology_first_title', 'Первый подзаголовок страницы Идеология'), ('Ideology_second_title', 'Второй подзаголовок страницы Идеология'), ('Ideology_info', 'Информационные блоки для страницы Идеология'), ('History_title', 'Подзаголовок страницы История'), ('History_info', 'Информационные блоки для страницы История'), ('Mail_send_to', 'Email для отправки вопросов на сайте')], max_length=40, unique=True, verbose_name='Выбор ключа настроек'),
        ),
        migrations.AlterField(
            model_name='settingsimagerelation',
            name='image_order',
            field=models.PositiveIntegerField(unique=True, verbose_name='Порядковый номер картинки на странице сверху вниз'),
        ),
    ]
