# Generated by Django 3.2.13 on 2022-06-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20220511_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('order',), 'verbose_name': 'Банер на главной странице', 'verbose_name_plural': 'Банеры на главной странице'},
        ),
    ]
