# Generated by Django 3.2.9 on 2021-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_banner_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button',
            field=models.CharField(choices=[('TICKETS', 'Билеты'), ('DETAILS', 'Подробнее'), ('READ', 'Читать')], default="TICKETS", max_length=40, verbose_name='Выбор типа кнопки'),
            preserve_default=False,
        ),
    ]
