# Generated by Django 3.2.7 on 2021-10-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211021_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoblock',
            name='block_order',
            field=models.PositiveIntegerField(verbose_name='Порядок отображения внутри блоков странице сверху вниз'),
        ),
        migrations.AddConstraint(
            model_name='infoblock',
            constraint=models.UniqueConstraint(fields=('block', 'block_order'), name='unique_order'),
        ),
    ]
