# Generated by Django 3.2.7 on 2021-10-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211018_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainsettings',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название (значение key)'),
        ),
    ]
