# Generated by Django 3.2.7 on 2021-10-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211021_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsimagerelation',
            name='image_order',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер картинки на странице сверху вниз'),
        ),
        migrations.AddConstraint(
            model_name='settingsimagerelation',
            constraint=models.UniqueConstraint(fields=('settings', 'image_order'), name='unique_image_order'),
        ),
    ]
