# Generated by Django 3.2.10 on 2021-12-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_settingemail_settingfirstscreen_settinggeneral_settingmain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
