name: backend lubimovka build and deploy

on:
  [push]


jobs:
  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} success!
                  ${{ github.event }}
                  ${{ github.event_name }}
                  ${{ github.event_path }}
